import type { KnowledgeNode, KnowledgeEdge } from './types';

// 全部知识点节点
export const KNOWLEDGE_NODES: KnowledgeNode[] = [
  // ===== Domain 1: Go 语言基础 (8 个) =====
  {
    id: '1-1',
    label: '基本语法',
    domain: 1,
    level: 1,
    mastery: 0,
    description: '变量、常量、控制流、函数定义等 Go 基础语法结构',
    importance: 5,
  },
  {
    id: '1-2',
    label: '复合类型',
    domain: 1,
    level: 1,
    mastery: 0,
    description: '数组、切片、映射、结构体等内置复合数据类型',
    importance: 5,
  },
  {
    id: '1-3',
    label: '接口',
    domain: 1,
    level: 2,
    mastery: 0,
    description: '接口定义、实现、类型断言与空接口用法',
    importance: 5,
  },
  {
    id: '1-4',
    label: '错误处理',
    domain: 1,
    level: 2,
    mastery: 0,
    description: 'error 接口、panic/recover、自定义错误与错误包装',
    importance: 4,
  },
  {
    id: '1-5',
    label: '泛型',
    domain: 1,
    level: 3,
    mastery: 0,
    description: '类型参数、约束、实例化与泛型最佳实践',
    importance: 4,
  },
  {
    id: '1-6',
    label: '反射',
    domain: 1,
    level: 3,
    mastery: 0,
    description: 'reflect 包基础、类型与值反射、动态调用',
    importance: 3,
  },
  {
    id: '1-7',
    label: 'unsafe/cgo',
    domain: 1,
    level: 4,
    mastery: 0,
    description: 'unsafe 包指针操作与 cgo 跨语言调用',
    importance: 2,
  },
  {
    id: '1-8',
    label: 'embed/指令',
    domain: 1,
    level: 4,
    mastery: 0,
    description: '//go:embed 与编译器指令的应用',
    importance: 2,
  },

  // ===== Domain 2: 并发编程 (8 个) =====
  {
    id: '2-1',
    label: 'goroutine',
    domain: 2,
    level: 1,
    mastery: 0,
    description: 'goroutine 启动、生命周期与轻量级线程模型',
    importance: 5,
  },
  {
    id: '2-2',
    label: 'channel',
    domain: 2,
    level: 1,
    mastery: 0,
    description: 'channel 类型、缓冲/非缓冲、关闭与范围遍历',
    importance: 5,
  },
  {
    id: '2-3',
    label: 'select',
    domain: 2,
    level: 2,
    mastery: 0,
    description: 'select 多路复用、超时控制与默认分支',
    importance: 4,
  },
  {
    id: '2-4',
    label: 'context',
    domain: 2,
    level: 2,
    mastery: 0,
    description: 'context 包、取消传播、超时与传值机制',
    importance: 5,
  },
  {
    id: '2-5',
    label: 'sync包',
    domain: 2,
    level: 2,
    mastery: 0,
    description: 'Mutex、RWMutex、WaitGroup、Once、Pool 等同步原语',
    importance: 4,
  },
  {
    id: '2-6',
    label: '并发模式',
    domain: 2,
    level: 3,
    mastery: 0,
    description: '扇出/扇入、流水线、worker pool 等常见并发模式',
    importance: 4,
  },
  {
    id: '2-7',
    label: '原子操作',
    domain: 2,
    level: 3,
    mastery: 0,
    description: 'sync/atomic 包、CAS 操作与内存序',
    importance: 3,
  },
  {
    id: '2-8',
    label: '调度器原理',
    domain: 2,
    level: 4,
    mastery: 0,
    description: 'GMP 模型、抢占调度与协作式调度细节',
    importance: 3,
  },

  // ===== Domain 3: 运行时与性能 (6 个) =====
  {
    id: '3-1',
    label: 'GC基础',
    domain: 3,
    level: 1,
    mastery: 0,
    description: 'Go GC 发展史、STW 与并发 GC 基本概念',
    importance: 4,
  },
  {
    id: '3-2',
    label: '三色标记',
    domain: 3,
    level: 2,
    mastery: 0,
    description: '三色标记清除算法、写屏障与插入/删除屏障',
    importance: 4,
  },
  {
    id: '3-3',
    label: '内存分配',
    domain: 3,
    level: 2,
    mastery: 0,
    description: 'TCMalloc 风格分配器、span 与 cache 层级',
    importance: 3,
  },
  {
    id: '3-4',
    label: 'pprof',
    domain: 3,
    level: 2,
    mastery: 0,
    description: 'CPU/堆/goroutine/阻塞/互斥性能剖析工具',
    importance: 4,
  },
  {
    id: '3-5',
    label: 'GMP调度',
    domain: 3,
    level: 3,
    mastery: 0,
    description: 'Goroutine/Machine/Processor 调度循环与调度时机',
    importance: 3,
  },
  {
    id: '3-6',
    label: '性能调优',
    domain: 3,
    level: 4,
    mastery: 0,
    description: '基准测试、逃逸分析、边界检查消除与编译器优化',
    importance: 3,
  },

  // ===== Domain 4: 工程实践 (6 个) =====
  {
    id: '4-1',
    label: '项目结构',
    domain: 4,
    level: 1,
    mastery: 0,
    description: '标准 Go 项目布局、包组织与依赖管理',
    importance: 4,
  },
  {
    id: '4-2',
    label: '单元测试',
    domain: 4,
    level: 1,
    mastery: 0,
    description: 'testing 包、表格驱动测试、覆盖率与子测试',
    importance: 4,
  },
  {
    id: '4-3',
    label: 'mock/bench',
    domain: 4,
    level: 2,
    mastery: 0,
    description: 'gomock 与基准测试编写、benchstat 分析',
    importance: 3,
  },
  {
    id: '4-4',
    label: 'CI/CD',
    domain: 4,
    level: 2,
    mastery: 0,
    description: 'GitHub Actions、GitLab CI、流水线集成与自动化',
    importance: 3,
  },
  {
    id: '4-5',
    label: '代码审查',
    domain: 4,
    level: 3,
    mastery: 0,
    description: 'Code Review 流程、静态分析工具与 lint 规则',
    importance: 3,
  },
  {
    id: '4-6',
    label: 'monorepo',
    domain: 4,
    level: 3,
    mastery: 0,
    description: 'monorepo 管理、Bazel/Turbo 与多模块协作',
    importance: 2,
  },

  // ===== Domain 5: 微服务与 RPC (6 个) =====
  {
    id: '5-1',
    label: 'HTTP服务',
    domain: 5,
    level: 1,
    mastery: 0,
    description: 'net/http 路由、中间件模式与 RESTful API 设计',
    importance: 5,
  },
  {
    id: '5-2',
    label: 'gRPC基础',
    domain: 5,
    level: 1,
    mastery: 0,
    description: 'Protocol Buffers、gRPC 通信模式与服务定义',
    importance: 4,
  },
  {
    id: '5-3',
    label: '流式RPC',
    domain: 5,
    level: 2,
    mastery: 0,
    description: '服务端/客户端/双向流式 RPC 与背压机制',
    importance: 3,
  },
  {
    id: '5-4',
    label: '服务发现',
    domain: 5,
    level: 2,
    mastery: 0,
    description: 'Consul/etcd 服务注册与发现、健康检查',
    importance: 3,
  },
  {
    id: '5-5',
    label: '链路追踪',
    domain: 5,
    level: 3,
    mastery: 0,
    description: 'OpenTelemetry、分布式追踪与 Trace 上下文传播',
    importance: 3,
  },
  {
    id: '5-6',
    label: '服务网格',
    domain: 5,
    level: 4,
    mastery: 0,
    description: 'Istio/Envoy sidecar 模式与服务网格架构',
    importance: 2,
  },

  // ===== Domain 6: 数据与存储 (6 个) =====
  {
    id: '6-1',
    label: 'database/sql',
    domain: 6,
    level: 1,
    mastery: 0,
    description: 'Go 标准数据库接口、连接池与事务管理',
    importance: 4,
  },
  {
    id: '6-2',
    label: 'ORM',
    domain: 6,
    level: 1,
    mastery: 0,
    description: 'GORM/Ent 等 ORM 框架、迁移与关联查询',
    importance: 4,
  },
  {
    id: '6-3',
    label: 'Redis',
    domain: 6,
    level: 2,
    mastery: 0,
    description: 'go-redis 客户端、数据结构与管道/事务操作',
    importance: 4,
  },
  {
    id: '6-4',
    label: '分库分表',
    domain: 6,
    level: 3,
    mastery: 0,
    description: 'ShardingSphere、分片键设计与跨分片查询',
    importance: 3,
  },
  {
    id: '6-5',
    label: '缓存策略',
    domain: 6,
    level: 3,
    mastery: 0,
    description: '缓存穿透/击穿/雪崩、本地缓存与分布式缓存',
    importance: 3,
  },
  {
    id: '6-6',
    label: '新SQL',
    domain: 6,
    level: 4,
    mastery: 0,
    description: 'TiDB/CockroachDB HTAP 与分布式 SQL 引擎',
    importance: 2,
  },

  // ===== Domain 7: 云原生 (6 个) =====
  {
    id: '7-1',
    label: 'Docker',
    domain: 7,
    level: 1,
    mastery: 0,
    description: '容器化原理、Dockerfile 优化与多阶段构建',
    importance: 5,
  },
  {
    id: '7-2',
    label: 'K8s核心',
    domain: 7,
    level: 1,
    mastery: 0,
    description: 'Pod/Service/Deployment/ConfigMap 等核心资源',
    importance: 5,
  },
  {
    id: '7-3',
    label: 'Helm',
    domain: 7,
    level: 2,
    mastery: 0,
    description: 'Chart 管理、模板引擎与发布/回滚策略',
    importance: 3,
  },
  {
    id: '7-4',
    label: 'Operator',
    domain: 7,
    level: 3,
    mastery: 0,
    description: 'Operator 模式、CRD 自定义资源与控制器循环',
    importance: 3,
  },
  {
    id: '7-5',
    label: 'Terraform',
    domain: 7,
    level: 3,
    mastery: 0,
    description: '基础设施即代码、声明式配置与状态管理',
    importance: 3,
  },
  {
    id: '7-6',
    label: '平台工程',
    domain: 7,
    level: 4,
    mastery: 0,
    description: '内部开发者平台、Backstage 与自助服务门户',
    importance: 2,
  },

  // ===== Domain 8: 系统设计 (6 个) =====
  {
    id: '8-1',
    label: '设计模式',
    domain: 8,
    level: 1,
    mastery: 0,
    description: '创建型/结构型/行为型模式的 Go 语言实现',
    importance: 4,
  },
  {
    id: '8-2',
    label: '分布式基础',
    domain: 8,
    level: 1,
    mastery: 0,
    description: 'CAP、一致性哈希、选举算法与复制协议',
    importance: 4,
  },
  {
    id: '8-3',
    label: '消息队列',
    domain: 8,
    level: 2,
    mastery: 0,
    description: 'Kafka/RabbitMQ 模型、生产者-消费者与重试',
    importance: 4,
  },
  {
    id: '8-4',
    label: '事件驱动',
    domain: 8,
    level: 2,
    mastery: 0,
    description: '事件溯源、CQRS 模式与事件总线实现',
    importance: 3,
  },
  {
    id: '8-5',
    label: '高可用',
    domain: 8,
    level: 3,
    mastery: 0,
    description: '熔断/限流/降级、多活架构与容灾策略',
    importance: 4,
  },
  {
    id: '8-6',
    label: '分布式事务',
    domain: 8,
    level: 3,
    mastery: 0,
    description: '二阶段提交、Saga 模式、TCC 与最终一致性',
    importance: 3,
  },
];

// 全部依赖边
export const KNOWLEDGE_EDGES: KnowledgeEdge[] = [
  // Domain 1: Go 语言基础
  { source: '1-1', target: '1-2', label: '基础→复合' },
  { source: '1-2', target: '1-3', label: '复合→接口' },
  { source: '1-3', target: '1-4', label: '接口→错误' },
  { source: '1-4', target: '1-5', label: '错误→泛型' },
  { source: '1-5', target: '1-6', label: '泛型→反射' },
  { source: '1-6', target: '1-7', label: '反射→unsafe' },
  { source: '1-7', target: '1-8', label: 'unsafe→embed' },

  // Domain 2: 并发编程
  { source: '2-1', target: '2-2', label: 'goroutine→channel' },
  { source: '2-2', target: '2-3', label: 'channel→select' },
  { source: '2-3', target: '2-4', label: 'select→context' },
  { source: '2-4', target: '2-5', label: 'context→sync' },
  { source: '2-5', target: '2-6', label: 'sync→模式' },
  { source: '2-6', target: '2-7', label: '模式→原子' },
  { source: '2-7', target: '2-8', label: '原子→调度' },

  // Domain 3: 运行时与性能
  { source: '3-1', target: '3-2', label: 'GC→三色' },
  { source: '3-2', target: '3-3', label: '三色→内存' },
  { source: '3-3', target: '3-4', label: '内存→pprof' },
  { source: '3-4', target: '3-5', label: 'pprof→GMP' },
  { source: '3-5', target: '3-6', label: 'GMP→调优' },

  // Domain 4: 工程实践
  { source: '4-1', target: '4-2', label: '结构→测试' },
  { source: '4-2', target: '4-3', label: '测试→mock' },
  { source: '4-3', target: '4-4', label: 'mock→CI/CD' },
  { source: '4-4', target: '4-5', label: 'CI/CD→审查' },
  { source: '4-5', target: '4-6', label: '审查→monorepo' },

  // Domain 5: 微服务与 RPC
  { source: '5-1', target: '5-2', label: 'HTTP→gRPC' },
  { source: '5-2', target: '5-3', label: 'gRPC→流式' },
  { source: '5-3', target: '5-4', label: '流式→发现' },
  { source: '5-4', target: '5-5', label: '发现→追踪' },
  { source: '5-5', target: '5-6', label: '追踪→网格' },

  // Domain 6: 数据与存储
  { source: '6-1', target: '6-2', label: 'sql→ORM' },
  { source: '6-2', target: '6-3', label: 'ORM→Redis' },
  { source: '6-3', target: '6-4', label: 'Redis→分片' },
  { source: '6-4', target: '6-5', label: '分片→缓存' },
  { source: '6-5', target: '6-6', label: '缓存→新SQL' },

  // Domain 7: 云原生
  { source: '7-1', target: '7-2', label: 'Docker→K8s' },
  { source: '7-2', target: '7-3', label: 'K8s→Helm' },
  { source: '7-3', target: '7-4', label: 'Helm→Operator' },
  { source: '7-4', target: '7-5', label: 'Operator→Terraform' },
  { source: '7-5', target: '7-6', label: 'Terraform→平台' },

  // Domain 8: 系统设计
  { source: '8-1', target: '8-2', label: '模式→分布式' },
  { source: '8-2', target: '8-3', label: '分布式→MQ' },
  { source: '8-3', target: '8-4', label: 'MQ→事件' },
  { source: '8-4', target: '8-5', label: '事件→高可用' },
  { source: '8-5', target: '8-6', label: '高可用→分布式事务' },
];

// 按领域筛选节点
export function getNodesByDomain(domain: number): KnowledgeNode[] {
  return KNOWLEDGE_NODES.filter((n) => n.domain === domain);
}

// 按领域筛选边
export function getEdgesByDomain(domain: number): KnowledgeEdge[] {
  const domainNodeIds = new Set(
    KNOWLEDGE_NODES.filter((n) => n.domain === domain).map((n) => n.id),
  );
  return KNOWLEDGE_EDGES.filter(
    (e) => domainNodeIds.has(e.source) && domainNodeIds.has(e.target),
  );
}