-- Go 语言面试题种子数据
-- 覆盖 8 大领域、4 个难度层级，共 208 题
-- ID 从 1 开始连续递增

-- 领域编号: 1=Go语言基础, 2=并发编程, 3=运行时与性能, 4=工程实践, 5=微服务与RPC, 6=数据与存储, 7=云原生, 8=系统设计
-- 难度层级: 1=L1(入门), 2=L2(初级), 3=L3(中级), 4=L4(高级)

INSERT INTO questions (id, domain, level, topic, question, reference_answer, keywords, hints, tags, source) VALUES
-- ====================================================================
-- 领域 1: Go 语言基础 (ID 1-32)
-- L1 入门 (ID 1-8)
-- ====================================================================
(1, 1, 1, '基本语法', 'Go 语言中 make 和 new 的区别是什么？', 'make 用于创建 slice、map、channel 等引用类型，返回初始化后的值（非零值）；new 用于分配任意类型的零值内存，返回 *T 类型的指针。make 返回 T，new 返回 *T。', '["make", "new", "slice", "map", "channel"]', '["提示1: make 只能用于三种引用类型", "提示2: new 返回的是指针"]', '["语法", "内存分配"]', 'official'),
(2, 1, 1, '变量声明', 'Go 语言中短变量声明 := 和 var 声明有什么区别？', ':= 用于函数内声明并初始化变量，类型由编译器推断；var 可用于函数内外声明，支持显式类型声明和零值初始化。:= 不能用于包级别变量。', '["短变量声明", "var", "类型推断", "变量声明"]', '["提示1: := 有作用域限制", "提示2: var 可以在包级别使用"]', '["语法", "变量"]', 'official'),
(3, 1, 1, '数据类型', 'Go 语言的基本数据类型有哪些？请列举。', 'Go 的基本数据类型包括：bool、string、int/int8/int16/int32/int64、uint/uint8/uint16/uint32/uint64、uintptr、byte（uint8 别名）、rune（int32 别名）、float32/float64、complex64/complex128。', '["基本类型", "byte", "rune", "int", "float"]', '["提示1: byte 是 uint8 的别名", "提示2: rune 是 int32 的别名"]', '["数据类型", "基础"]', 'official'),
(4, 1, 1, '控制结构', 'Go 语言中 for 循环有哪几种形式？', 'Go 只有 for 关键字，支持三种形式：1）for init; condition; post {}（类似 C 的 for）；2）for condition {}（类似 while）；3）for range {}（遍历 slice/map/channel/string）。没有 while 和 do-while 关键字。', '["for", "range", "循环", "控制结构"]', '["提示1: Go 没有 while 关键字", "提示2: range 可以遍历多种类型"]', '["语法", "控制流"]', 'official'),
(5, 1, 1, '函数', 'Go 函数支持多返回值吗？如何使用？', 'Go 原生支持多返回值，在函数签名中定义多个返回类型，调用时使用多个变量接收。常用于返回结果和错误值对，例如：func div(a, b int) (int, error) { ... }。', '["多返回值", "函数", "返回值"]', '["提示1: 多返回值是 Go 的重要特性", "提示2: 通常用于返回值和错误"]', '["函数", "语法"]', 'official'),
(6, 1, 1, '包管理', 'Go 中如何导入包？导入路径的规则是什么？', '使用 import 关键字导入包，导入路径是模块路径下的相对路径。支持单行导入 import "fmt" 和分组导入 import ( "fmt"; "os" )。包名通常与导入路径的最后一段一致。', '["import", "包管理", "模块", "导入路径"]', '["提示1: 包名通常与目录名一致", "提示2: 支持分组导入"]', '["包管理", "模块"]', 'official'),
(7, 1, 1, '字符串', 'Go 中 string 类型是不可变的吗？如何高效拼接字符串？', 'Go 的 string 是不可变的，一旦创建不能修改。高效拼接字符串推荐使用 strings.Builder（最推荐，底层避免多次内存分配）或 bytes.Buffer，其次是用 append 配合 []byte，避免使用 + 号大量拼接。', '["string", "不可变", "strings.Builder", "拼接"]', '["提示1: string 不可直接修改", "提示2: + 号拼接大量字符串效率低"]', '["字符串", "性能"]', 'official'),
(8, 1, 1, '数组与切片', 'Go 中数组和切片有什么区别？', '数组长度固定，是值类型，传递时复制整个数组；切片长度可变，是引用类型（底层指向数组），传递时共享底层数据。切片由指针、长度和容量三部分组成。', '["数组", "切片", "引用类型", "值类型"]', '["提示1: 数组长度是类型的一部分", "提示2: 切片包含指针/长度/容量"]', '["数据结构", "切片", "数组"]', 'official'),

-- L2 初级 (ID 9-16)
(9, 1, 2, '结构体', 'Go 中结构体支持继承吗？如何实现类似面向对象的行为？', 'Go 不支持传统的类继承，但通过结构体嵌套（组合）实现代码复用，通过接口实现多态。Go 推崇组合优于继承的设计哲学，使用嵌入字段可以实现方法提升。', '["结构体", "组合", "继承", "面向对象"]', '["提示1: Go 使用组合代替继承", "提示2: 嵌入字段的方法会被提升"]', '["结构体", "面向对象"]', 'official'),
(10, 1, 2, '方法', 'Go 中方法和函数的区别是什么？值接收者和指针接收者有何不同？', '方法有接收者（receiver），函数没有。值接收者对副本操作，不修改原值；指针接收者可修改原值，且避免复制大结构体。选择原则：需要修改接收者或结构体较大时用指针接收者。', '["方法", "接收者", "值接收者", "指针接收者"]', '["提示1: 值接收者操作的是副本", "提示2: 指针接收者可修改原值"]', '["方法", "OOP"]', 'official'),
(11, 1, 2, '接口', 'Go 中接口是如何实现 duck typing 的？空接口 interface{} 有什么用途？', 'Go 的接口是隐式实现，只要类型实现了接口的所有方法，就自动满足该接口，无需显式声明。空接口 interface{} 没有方法约束，可以存储任意类型，类似 void*。', '["接口", "duck typing", "空接口", "interface{}"]', '["提示1: Go 的接口是隐式实现", "提示2: 空接口可表示任意类型"]', '["接口", "类型系统"]', 'official'),
(12, 1, 2, 'defer', 'Go 中 defer 的执行顺序和特点是什么？defer 常用于哪些场景？', 'defer 在函数返回前执行，多个 defer 按后进先出（LIFO）顺序执行。defer 的参数在声明时求值。常用于资源释放、关闭文件、解锁互斥锁、recover 异常等场景。', '["defer", "LIFO", "资源释放", "recover"]', '["提示1: defer 是后进先出", "提示2: defer 的参数立即求值"]', '["语法", "资源管理"]', 'official'),
(13, 1, 2, '错误处理', 'Go 中 error 接口是如何定义的？如何处理错误？', 'error 是内置接口，定义：type error interface { Error() string }。Go 使用多返回值返回错误，调用者通过 if err != nil 检查。推荐早期返回（early return）模式，避免深层嵌套。', '["error", "错误处理", "Error()", "早期返回"]', '["提示1: error 是一个内置接口", "提示2: Go 不使用 try-catch"]', '["错误处理", "异常"]', 'official'),
(14, 1, 2, '类型断言', 'Go 中类型断言的语法和使用场景是什么？', '类型断言用于从接口类型提取具体类型，语法：value, ok := x.(T)。ok 为 true 表示成功，false 表示失败（不会 panic）。常用于类型分支 switch x.(type) 中。', '["类型断言", "接口", "类型转换", "类型分支"]', '["提示1: 带 ok 的断言不会 panic", "提示2: 可用 switch type 做类型分支"]', '["类型系统", "接口"]', 'official'),
(15, 1, 2, '常量与 iota', 'Go 中 iota 是什么？如何使用 iota 定义枚举？', 'iota 是 Go 中的常量计数器，在 const 块中每行自增 1。常用于定义枚举值，支持跳过和位移操作。例如：const ( A = iota; B; C ) 得到 A=0, B=1, C=2。', '["iota", "常量", "枚举", "自增"]', '["提示1: iota 从 0 开始", "提示2: iota 在 const 块中逐行递增"]', '["常量", "枚举"]', 'official'),
(16, 1, 2, '可见性', 'Go 中如何控制标识符的可见性（公有/私有）？', 'Go 通过标识符首字母大小写控制可见性：首字母大写为公有（public），可被其他包访问；首字母小写为私有（private），仅包内可见。这是 Go 唯一的访问控制机制。', '["可见性", "公有", "私有", "首字母大小写"]', '["提示1: 大写字母开头表示公有", "提示2: 小写字母开头表示私有"]', '["包管理", "可见性"]', 'official'),

-- L3 中级 (ID 17-24)
(17, 1, 3, '反射', 'Go 中 reflect 包如何获取和修改结构体字段值？', '使用 reflect.ValueOf() 获取反射值对象，通过 Elem() 获取指针指向的值，FieldByName() 访问字段。修改值需要确保传入的是指针且值可设置（CanSet）。TypeOf() 可获取类型信息。', '["reflect", "反射", "ValueOf", "TypeOf", "Elem"]', '["提示1: 修改值需要传入指针", "提示2: 使用 CanSet 检查可设置性"]', '["反射", "高级特性"]', 'official'),
(18, 1, 3, '标签', 'Go 中结构体标签（struct tag）的用途是什么？如何读取？', '结构体标签是字段的元信息，用反引号包裹，格式为 key:"value"。通过 reflect 包读取，常用场景包括 JSON 序列化（json:"field_name"）、ORM 映射、验证等。', '["struct tag", "反射", "元信息", "JSON"]', '["提示1: 标签用反引号定义", "提示2: 通过 reflect 包读取标签"]', '["结构体", "反射", "序列化"]', 'official'),
(19, 1, 3, '泛型', 'Go 1.18 泛型的语法和使用限制是什么？', '泛型使用方括号声明类型参数 [T any]，约束可以是 any（任意类型）或自定义接口。支持泛型函数、泛型类型和方法。限制：不能用于 switch type 判断具体类型，泛型类型的方法不能有额外类型参数。', '["泛型", "类型参数", "约束", "Go 1.18"]', '["提示1: 使用 [] 声明类型参数", "提示2: 类型约束用接口定义"]', '["泛型", "类型系统"]', 'official'),
(20, 1, 3, '闭包', 'Go 中闭包的实现原理和常见陷阱是什么？', '闭包是函数与其引用环境的组合。Go 中闭包捕获的是变量的引用而非值，可能导致 goroutine 中使用循环变量时的经典错误。解决方法：在循环内创建局部变量或使用参数传递。', '["闭包", "变量捕获", "循环变量", "goroutine"]', '["提示1: 闭包捕获的是变量引用", "提示2: 循环变量共享问题"]', '["函数", "闭包", "陷阱"]', 'official'),
(21, 1, 3, 'init 函数', 'Go 中 init 函数的作用和执行顺序是什么？', 'init 函数在包初始化时自动执行，无参数无返回值。执行顺序：先初始化导入的包，按导入顺序；一个包内有多个 init 按文件名字典序执行；一个文件内多个 init 按出现顺序执行。', '["init", "初始化", "包加载", "执行顺序"]', '["提示1: init 在 main 之前执行", "提示2: init 无参数无返回值"]', '["初始化", "包管理"]', 'official'),
(22, 1, 3, '空结构体', 'Go 中空结构体 struct{} 的用途和内存占用是什么？', '空结构体 struct{} 不占用任何内存空间（零内存），常用于仅需标记的场景：作为 channel 的信号（chan struct{}）、map 的集合键（map[K]struct{}）、或者实现只包含方法的类型。', '["空结构体", "struct{}", "零内存", "集合"]', '["提示1: struct{} 不占用内存", "提示2: 常用于 channel 信号"]', '["数据结构", "优化", "内存"]', 'official'),
(23, 1, 3, '类型嵌套', 'Go 中结构体匿名字段（嵌入）的内部机制是什么？', '匿名字段使用类型名而非字段名直接嵌入，嵌入类型的所有方法会被提升到外部类型。如果外部类型定义了同名方法，会覆盖嵌入类型的方法。支持同时嵌入多个同接口类型。', '["匿名字段", "嵌入", "方法提升", "覆盖"]', '["提示1: 嵌入类型的方法被提升", "提示2: 同名方法会覆盖"]', '["结构体", "组合", "方法"]', 'official'),
(24, 1, 3, '类型转换', 'Go 中类型转换和类型断言的区别是什么？', '类型转换用于具体类型之间（如 int 转 int64），语法 T(x)，编译器在编译时检查。类型断言用于接口类型到具体类型，语法 x.(T)，在运行时检查。转换针对具体类型，断言针对接口。', '["类型转换", "类型断言", "编译时", "运行时"]', '["提示1: 类型转换编译时检查", "提示2: 类型断言运行时检查"]', '["类型系统", "语法"]', 'official'),

-- L4 高级 (ID 25-32)
(25, 1, 4, '类型系统', 'Go 的类型系统有哪些独特的设计哲学？', 'Go 采用结构类型系统（structural typing），接口满足是隐式的。没有类型层次体系，无继承和多态。不支持运算符重载和隐式类型转换。类型安全且高效，编译器可做大量静态检查。', '["类型系统", "结构类型", "隐式接口", "设计哲学"]', '["提示1: Go 没有继承体系", "提示2: 接口满足是结构化的"]', '["类型系统", "设计哲学"]', 'official'),
(26, 1, 4, '内存对齐', 'Go 中内存对齐的规则是什么？如何优化结构体字段顺序？', 'Go 编译器会对结构体字段进行内存对齐，字段地址是其对齐值的倍数。通过将大字段（如 int64/float64）放在前面，小字段放在后面，减少填充字节（padding），优化结构体大小。', '["内存对齐", "padding", "结构体优化", "对齐值"]', '["提示1: 大字段放前面减少填充", "提示2: unsafe.Sizeof 可查看大小"]', '["内存", "性能优化", "结构体"]', 'official'),
(27, 1, 4, '编译器优化', 'Go 编译器（gc）有哪些主要的优化策略？', 'Go 编译器优化包括：逃逸分析（将堆分配转为栈分配）、内联优化（小函数直接展开）、死代码消除、边界检查消除、常量传播、循环优化等。可以使用 -gcflags="-m" 查看优化决策。', '["编译器优化", "逃逸分析", "内联", "边界检查消除"]', '["提示1: -gcflags=-m 可查看优化", "提示2: 逃逸分析决定堆栈分配"]', '["编译器", "性能优化"]', 'official'),
(28, 1, 4, 'go:linkname', 'go:linkname 指令的作用和风险是什么？', 'go:linkname 允许将一个函数链接到另一个包中未导出的函数，通过 //go:linkname localname remote.pkg.remoteName 实现。风险包括：破坏封装性、兼容性无保证、版本更新可能导致崩溃。', '["go:linkname", "链接", "未导出", "风险"]', '["提示1: 可访问其他包的私有函数", "提示2: Go 团队不保证兼容性"]', '["编译指令", "高级", "风险"]', 'official'),
(29, 1, 4, '汇编', 'Go 的 plan9 汇编如何与 Go 代码交互？', 'Go 使用 plan9 汇编风格，通过 //go:noescape 和 //go:nosplit 等指令控制。汇编函数在 .s 文件中实现，Go 中声明函数原型即可调用。参数通过栈传递（而非寄存器），FP 伪寄存器访问参数。', '["plan9 汇编", "go:noescape", "FP", "汇编交互"]', '["提示1: 参数通过栈传递", "提示2: FP 伪寄存器访问参数"]', '["汇编", "底层", "高级"]', 'official'),
(30, 1, 4, 'cgo', 'cgo 的使用场景和性能开销是什么？', 'cgo 允许 Go 调用 C 代码，通过 import "C" 实现。使用场景包括：调用现有 C 库、系统调用、性能关键路径用 C 实现。性能开销大：goroutine 需绑定到系统线程、切换 C 栈、参数复制等。', '["cgo", "C 语言", "性能开销", "系统调用"]', '["提示1: cgo 调用需要 M 绑定线程", "提示2: 频繁调用 cgo 性能损失大"]', '["cgo", "互操作", "性能"]', 'official'),
(31, 1, 4, 'unsafe 包', 'unsafe 包的核心功能和潜在危险是什么？', 'unsafe 包提供绕过 Go 类型安全的能力：unsafe.Pointer 可在任意指针类型间转换，uintptr 可进行指针运算。危险在于：破坏内存安全、不保证跨版本兼容、可能导致难以调试的崩溃。', '["unsafe", "unsafe.Pointer", "指针运算", "内存安全"]', '["提示1: uintptr 可进行指针运算", "提示2: unsafe 代码不可移植"]', '["unsafe", "指针", "高级"]', 'official'),
(32, 1, 4, 'ABI', 'Go 1.17+ 的 register ABI 是什么？有什么影响？', '寄存器 ABI（Application Binary Interface）是 Go 1.17 引入的新调用约定，使用寄存器而非栈传递函数参数和返回值。影响：性能提升 5-15%，减少栈使用，优化与汇编交互方式。', '["ABI", "寄存器", "调用约定", "性能提升"]', '["提示1: 寄存器传参替代栈传参", "提示2: Go 1.17 开始引入"]', '["底层", "ABI", "性能优化"]', 'official'),

-- ====================================================================
-- 领域 2: 并发编程 (ID 33-64)
-- L1 入门 (ID 33-40)
-- ====================================================================
(33, 2, 1, 'goroutine', '什么是 goroutine？与线程的区别是什么？', 'goroutine 是 Go 的轻量级并发执行单元，由 Go 运行时调度。相比线程：栈初始仅几 KB（可动态增长），创建销毁成本极低，由 Go 运行时中的 M:N 调度器将 goroutine 映射到 OS 线程。', '["goroutine", "线程", "轻量级", "并发"]', '["提示1: goroutine 栈初始极小", "提示2: 由 Go 运行时调度而非 OS"]', '["并发", "goroutine"]', 'official'),
(34, 2, 1, 'channel', 'Go 中 channel 的基本使用方式和类型有哪些？', 'channel 是 Go 的 CSP 通信原语，用于 goroutine 间通信。类型包括：无缓冲通道（make(chan T)）和有缓冲通道（make(chan T, cap)）。操作符 <- 用于发送和接收，close() 关闭通道。', '["channel", "CSP", "无缓冲", "有缓冲"]', '["提示1: 无缓冲通道同步通信", "提示2: 有缓冲通道异步通信"]', '["并发", "channel"]', 'official'),
(35, 2, 1, 'go 关键字', '如何使用 go 关键字启动 goroutine？注意事项是什么？', '在函数调用前加 go 关键字即可启动 goroutine：go myFunc()。注意事项：主函数退出后所有 goroutine 终止；需使用 sync.WaitGroup 或 channel 同步等待；goroutine 内的 panic 会导致整个程序崩溃。', '["go 关键字", "启动 goroutine", "并发执行", "注意"]', '["提示1: main 返回后 goroutine 终止", "提示2: 需要同步机制等待完成"]', '["并发", "goroutine"]', 'official'),
(36, 2, 1, '同步原语', 'sync 包提供了哪些基本的同步原语？', 'sync 包主要提供：Mutex（互斥锁）、RWMutex（读写锁）、WaitGroup（等待组）、Once（单次执行）、Cond（条件变量）、Pool（对象池）和 Map（并发安全 map）。', '["sync", "Mutex", "WaitGroup", "Once", "RWMutex"]', '["提示1: Mutex 是互斥锁", "提示2: WaitGroup 等待 goroutine 完成"]', '["同步", "并发", "sync"]', 'official'),
(37, 2, 1, '竞态条件', '什么是数据竞态（data race）？如何检测？', '数据竞态是多个 goroutine 并发访问同一变量且至少一个是写操作。Go 提供 race detector，使用 go run -race 或 go build -race 启用。检测到竞态会输出详细报告，包括 goroutine 调用栈。', '["data race", "竞态条件", "race detector", "-race"]', '["提示1: race detector 运行时检测", "提示2: 生产环境建议关闭 -race"]', '["并发", "竞态", "调试"]', 'official'),
(38, 2, 1, '并发安全', '什么是并发安全？如何保证共享变量的并发安全？', '并发安全指代码在多 goroutine 并发访问时行为正确。保证方式：1）使用 sync.Mutex/RWMutex 加锁；2）使用 channel 通信；3）使用原子操作（sync/atomic）；4）避免共享（每个 goroutine 使用本地变量）。', '["并发安全", "互斥锁", "原子操作", "channel"]', '["提示1: 加锁是最常用的方式", "提示2: 原子操作适合简单场景"]', '["并发安全", "同步"]', 'official'),
(39, 2, 1, '死锁', 'Go 中死锁产生的原因是什么？如何避免？', '死锁产生条件：互斥、持有并等待、不可剥夺、循环等待。在 Go 中常见于：channel 收发不匹配、锁顺序不一致。避免方法：统一锁顺序、使用超时机制、减少锁持有时间、使用 defer 解锁。', '["死锁", "死锁条件", "锁顺序", "超时"]', '["提示1: 锁顺序不一致是常见原因", "提示2: channel 收发不匹配会死锁"]', '["死锁", "并发问题"]', 'official'),
(40, 2, 1, 'select', 'select 语句的作用和使用注意事项是什么？', 'select 用于同时监听多个 channel 的收发操作，随机选择一个可执行的 case。如果多个 case 同时满足，随机选择。空 select{} 会永久阻塞。default 分支在无 case 满足时执行，避免阻塞。', '["select", "多路复用", "channel", "default"]', '["提示1: select 随机选择就绪 case", "提示2: default 用于非阻塞操作"]', '["并发", "select", "channel"]', 'official'),

-- L2 初级 (ID 41-48)
(41, 2, 2, 'WaitGroup', 'sync.WaitGroup 的实现原理和使用方法是什么？', 'WaitGroup 通过内部计数器实现等待机制。Add(delta) 增加计数器，Done() 减 1（等价于 Add(-1)），Wait() 阻塞直到计数器为 0。计数器的增减和等待必须保证正确配对。', '["WaitGroup", "Add", "Done", "Wait", "计数器"]', '["提示1: Wait 阻塞到计数器归零", "提示2: Done 在 defer 中调用更安全"]', '["同步", "WaitGroup", "并发"]', 'official'),
(42, 2, 2, 'Mutex', 'sync.Mutex 和 sync.RWMutex 的区别及适用场景是什么？', 'Mutex 是互斥锁，同一时间只有一个 goroutine 能获取锁。RWMutex 是读写锁：读锁可被多个 goroutine 同时获取，写锁互斥（不能同时有读或写）。适用场景：读多写少用 RWMutex，读写均衡用 Mutex。', '["Mutex", "RWMutex", "读写锁", "互斥锁"]', '["提示1: RWMutex 适合读多写少", "提示2: 写锁与所有锁互斥"]', '["同步", "锁"]', 'official'),
(43, 2, 2, 'Once', 'sync.Once 的原理和使用场景是什么？', 'sync.Once 保证某个函数只被执行一次，即使多个 goroutine 同时调用。内部通过原子操作和互斥锁实现，使用 Do(f) 方法执行。常见场景：单例模式、延迟初始化、配置加载。', '["Once", "Do", "单次执行", "单例"]', '["提示1: Do 保证 f 只执行一次", "提示2: Once 内部使用原子操作+锁"]', '["同步", "设计模式"]', 'official'),
(44, 2, 2, '原子操作', 'sync/atomic 包提供了哪些原子操作？与加锁相比有什么优势？', 'atomic 包提供：Add（原子增减）、CompareAndSwap（CAS）、Load/Store（原子读写）、Swap（交换）。优势：无锁化，不涉及上下文切换，性能远优于 Mutex；劣势：仅支持简单操作，复杂场景仍需锁。', '["atomic", "CAS", "原子操作", "无锁"]', '["提示1: CAS 是 CompareAndSwap", "提示2: 原子操作性能高于锁"]', '["原子操作", "并发", "性能"]', 'official'),
(45, 2, 2, 'channel 方向', 'Go 中如何定义只读和只写 channel？有什么用途？', '通过类型定义限制 channel 方向：只读 <-chan T，只写 chan<- T。在函数参数中使用方向限制，增强类型安全性，明确职责。编译器会检查方向是否匹配，违反会导致编译错误。', '["只读 channel", "只写 channel", "channel 方向"]', '["提示1: <-chan 表示只读", "提示2: chan<- 表示只写"]', '["channel", "类型安全"]', 'official'),
(46, 2, 2, 'context', 'context 包的作用是什么？如何创建带取消的 context？', 'context 用于传递请求范围的值、取消信号和超时控制。创建方式：context.Background() 根 context、context.WithCancel() 返回可取消的 context、context.WithTimeout() 带超时、context.WithValue() 传值。', '["context", "取消", "超时", "传值"]', '["提示1: WithCancel 返回 cancel 函数", "提示2: WithTimeout 自动超时取消"]', '["并发", "context"]', 'official'),
(47, 2, 2, 'goroutine 泄漏', '什么是 goroutine 泄漏？如何避免？', 'goroutine 泄漏是指 goroutine 一直阻塞无法退出，导致内存持续增长。常见原因：从无返回的 channel 读、向无缓冲 channel 写无消费者、for-select 无退出条件。避免方法：确保有退出机制、使用 context 控制。', '["goroutine 泄漏", "内存泄漏", "阻塞", "context"]', '["提示1: channel 操作不匹配导致阻塞", "提示2: select 加 default 避免阻塞"]', '["内存泄漏", "goroutine", "问题排查"]', 'official'),
(48, 2, 2, '并发模式', '什么是 fan-in/fan-out 并发模式？如何实现？', 'fan-out 是多个 goroutine 从同一个 channel 读取数据并行处理，fan-in 是将多个 channel 的结果合并到一个 channel。实现：fan-out 用多个 worker goroutine 共享输入 channel；fan-in 用 select 或 merge goroutine。', '["fan-in", "fan-out", "并发模式", "pipeline"]', '["提示1: fan-out 是分发任务", "提示2: fan-in 是汇总结果"]', '["并发模式", "设计模式"]', 'official'),

-- L3 中级 (ID 49-56)
(49, 2, 3, '调度模型', 'Go 运行时 GMP 调度模型是什么？', 'GMP 模型：G（goroutine）轻量级协程、M（machine）OS 线程、P（processor）调度上下文。M 需绑定 P 才能执行 G。P 维护本地 runqueue，全局 runqueue 存储待执行 G。调度器通过 work stealing 和 hand off 机制实现负载均衡。', '["GMP", "G", "M", "P", "work stealing"]', '["提示1: P 是调度的核心", "提示2: work stealing 实现负载均衡"]', '["调度", "GMP", "运行时"]', 'official'),
(50, 2, 3, 'work stealing', 'Go 调度器 work stealing 机制的触发时机和过程是什么？', '当 P 的本地队列为空时，会尝试从其他 P 的队列（或全局队列、网络轮询器）中窃取一半 goroutine。触发时机包括：P 空闲、syscall 返回后。窃取以 1/2 的比例进行，保证负载均衡。', '["work stealing", "调度", "负载均衡", "本地队列"]', '["提示1: 偷取一半的 goroutine", "提示2: 从全局队列和网络轮询器也可获取"]', '["调度", "GMP", "并发"]', 'official'),
(51, 2, 3, '并发控制', '如何控制 goroutine 的并发数量？有哪些方式？', '控制并发数量的方式：1）有缓冲 channel 作为信号量；2）使用 worker pool 模式；3）使用第三方库如 errgroup、semaphore。常用：通过 buffered channel 的容量限制同时执行的 goroutine 数。', '["并发控制", "信号量", "worker pool", "限制"]', '["提示1: 有缓冲 channel 可作为信号量", "提示2: errgroup 可管理并发出错"]', '["并发控制", "goroutine", "限流"]', 'official'),
(52, 2, 3, 'channel 底层', 'Go 中 channel 的底层数据结构是什么？', 'channel 底层由 hchan 结构体表示，包含：循环缓冲区（buf，用于有缓冲）、发送/接收等待队列（sendq/recvq）、互斥锁（lock）、元素大小和容量等字段。发送/接收操作通过 mutex 加锁保证并发安全。', '["hchan", "channel 底层", "循环缓冲区", "等待队列"]', '["提示1: hchan 包含发送和接收队列", "提示2: channel 操作有 mutex 保护"]', '["底层", "channel", "数据结构"]', 'official'),
(53, 2, 3, 'sync.Map', 'sync.Map 的适用场景和内部实现是什么？', 'sync.Map 适合读多写少且 key 稳定的场景，内部采用读写分离：read 部分使用 atomic 操作无锁读，dirty 部分需要加锁写。通过 misses 计数决定何时将 dirty 提升为 read。自带延迟删除。', '["sync.Map", "并发 map", "读写分离", "atomic"]', '["提示1: 读操作无锁", "提示2: 适用读多写少场景"]', '["并发", "sync.Map", "数据结构"]', 'official'),
(54, 2, 3, 'errgroup', 'golang.org/x/sync/errgroup 的用法和原理是什么？', 'errgroup 提供带错误传播的并发执行机制。Go(func) 启动 goroutine，Wait() 等待全部完成并返回第一个非 nil 错误。内部结合 context 实现，任一 goroutine 出错可取消其他 goroutine。', '["errgroup", "错误传播", "并发取消", "Wait"]', '["提示1: 返回第一个错误", "提示2: 结合 context 传播取消"]', '["并发", "错误处理"]', 'official'),
(55, 2, 3, '定时器', 'Go 中 time.Timer 和 time.Ticker 的区别和内部实现是什么？', 'Timer 是单次定时器，到期触发一次事件；Ticker 是周期性定时器，每隔指定时间触发。底层使用时间堆（timers bucket，四叉堆）管理，每个 P 维护一个 timer 堆，timer 触发时调度对应 goroutine。', '["Timer", "Ticker", "时间堆", "定时器"]', '["提示1: Timer 触发一次", "提示2: Ticker 周期触发"]', '["定时器", "并发", "运行时"]', 'official'),
(56, 2, 3, '信号量', 'Go 中信号量的实现方式有哪些？', 'Go 中信号量的实现方式：1）有缓冲 channel（容量作为计数值）；2）golang.org/x/sync/semaphore（基于信号量实现加权信号量）；3）sync.Cond 配合计数变量。信号量用于控制并发访问资源的数量。', '["信号量", "semaphore", "channel", "并发控制"]', '["提示1: 有缓冲 channel 可作为信号量", "提示2: x/sync/semaphore 提供加权信号量"]', '["并发控制", "信号量"]', 'official'),

-- L4 高级 (ID 57-64)
(57, 2, 4, '内存模型', 'Go 内存模型中 happens-before 原则是什么？', 'happens-before 定义了操作的偏序关系，用于判断数据竞态。关键规则：1）同一个 goroutine 内的操作按代码顺序 happens-before；2）对 channel 的发送操作 happens-before 对应的接收完成；3）mutex 解锁 happens-before 后续加锁；4）WaitGroup 的 Done 调用 happens-before Wait 返回。', '["happens-before", "内存模型", "同步语义", "数据竞态"]', '["提示1: channel 发送先于接收", "提示2: 解锁先于后续加锁"]', '["内存模型", "并发", "理论"]', 'official'),
(58, 2, 4, '调度器演进', 'Go 调度器从 GM 到 GMP 模型的演进关键改进是什么？', 'GM 模型（Go 1.0）所有 goroutine 共享全局队列，需要全局锁，缓存在核间频繁失效。GMP 模型（Go 1.1+）引入 P 处理器，每个 P 有本地队列，通过 work stealing 减少锁竞争，大幅提升并发性能。', '["GMP 演进", "GM 模型", "P 处理器", "性能改进"]', '["提示1: GM 模型有全局锁瓶颈", "提示2: GMP 引入本地队列减少竞争"]', '["调度器", "历史演进", "性能"]', 'official'),
(59, 2, 4, '网络轮询', 'Go 运行时网络轮询器（netpoller）的实现原理是什么？', 'netpoller 使用操作系统 IO 多路复用机制（Linux epoll、Darwin kqueue、Windows IOCP）实现非阻塞网络 IO。goroutine 发起 IO 操作时，如果无法立即完成，G 会进入等待队列，P 继续调度其他 G。IO 就绪后 netpoller 唤醒等待的 G。', '["netpoller", "epoll", "非阻塞 IO", "网络轮询"]', '["提示1: 不同平台使用不同机制", "提示2: 避免阻塞 M 提高并发"]', '["网络", "IO", "调度", "运行时"]', 'official'),
(60, 2, 4, 'syscall 处理', 'Go 运行时如何处理阻塞的系统调用？', '进行阻塞 syscall 时，M 会与 P 解绑（hand off），P 去调度其他 M 执行 G。syscall 返回后，G 尝试获取之前的 P，如果被占用则进入全局队列。这种机制保证系统调用不阻塞其他 goroutine 的执行。', '["syscall", "hand off", "M 解绑", "阻塞"]', '["提示1: syscall 时 M 与 P 解绑", "提示2: P 继续调度其他 M"]', '["调度", "系统调用", "运行时"]', 'official'),
(61, 2, 4, '锁优化', 'Go 中 Mutex 的饥饿模式和正常模式是什么？', '正常模式下，goroutine 自旋几次后仍未获取锁则进入等待队列，新到的 goroutine 通过 CAS 更有可能获得锁，可能导致等待队列中的 goroutine 长时间饥饿。饥饿模式下，锁直接交给等待队列头部的 goroutine，新 goroutine 不自旋直接排队。饥饿模式防止极端延迟。', '["Mutex 饥饿", "正常模式", "自旋", "公平性"]', '["提示1: 正常模式性能好但不公平", "提示2: 饥饿模式保证公平性"]', '["Mutex", "锁优化", "并发"]', 'official'),
(62, 2, 4, 'channel 高级', 'Go 中 nil channel 和 closed channel 的行为区别是什么？', 'nil channel：发送和接收都会永久阻塞；closed channel：发送会导致 panic，接收会立即返回零值（可配合 ok 判断是否已关闭）。关闭一个已关闭的 channel 也会 panic。select 中 nil channel 永远不会被选中。', '["nil channel", "closed channel", "panic", "阻塞"]', '["提示1: nil channel 发送/接收均阻塞", "提示2: closed channel 发送会 panic"]', '["channel", "高级", "陷阱"]', 'official'),
(63, 2, 4, 'lock-free', 'Go 中如何实现无锁数据结构？', '无锁数据结构使用 atomic 包的 CAS（CompareAndSwap）操作实现，避免 Mutex 的开销。常见实现：无锁栈（Treiber stack）、无锁队列（Michael-Scott queue）。核心思想是用 CAS 循环替代锁，需要处理 ABA 问题。', '["lock-free", "CAS", "无锁数据结构", "ABA 问题"]', '["提示1: CAS 是无锁的核心", "提示2: ABA 问题需版本号解决"]', '["无锁", "并发", "高级"]', 'official'),
(64, 2, 4, '并发安全设计', 'Go 并发安全设计的核心哲学是什么？', 'Go 的并发哲学："Do not communicate by sharing memory; instead, share memory by communicating"（不要通过共享内存来通信，而应通过通信来共享内存）。核心思想是通过 channel 在 goroutine 间传递数据所有权，而不是通过锁保护共享数据。但 Go 也在 sync 包提供了传统同步原语。', '["CSP", "通信顺序进程", "共享内存", "channel 哲学"]', '["提示1: 通过通信共享内存", "提示2: channel 传递数据所有权"]', '["并发哲学", "CSP", "设计理念"]', 'official'),

-- ====================================================================
-- 领域 3: 运行时与性能 (ID 65-92)
-- L1 入门 (ID 65-71)
-- ====================================================================
(65, 3, 1, 'GC 基础', 'Go 使用什么垃圾回收算法？有什么特点？', 'Go 使用并发、三色标记-清除（tricolor mark-and-sweep）算法，特点：1）并发执行，与用户代码并行；2）使用写屏障（write barrier）保证并发正确性；3）非分代、非移动式（不压缩）；4）低延迟优先，默认为全量 GC。', '["GC", "三色标记", "写屏障", "并发 GC"]', '["提示1: Go 是标记-清除算法", "提示2: GC 与用户代码并发执行"]', '["GC", "内存管理", "运行时"]', 'official'),
(66, 3, 1, '栈与堆', 'Go 中变量分配在栈上还是堆上由什么决定？', '由逃逸分析（escape analysis）决定。如果变量的作用域局限于函数内部且不会逃逸，则分配在栈上；如果变量的地址被返回、存储到堆或全局变量中（即逃逸），则分配在堆上。可用 -gcflags="-m" 查看逃逸分析结果。', '["逃逸分析", "栈", "堆", "内存分配"]', '["提示1: 栈上分配更高效", "提示2: -gcflags=-m 可查看逃逸"]', '["内存管理", "逃逸分析", "性能"]', 'official'),
(67, 3, 1, 'GOROOT 与 GOPATH', 'GOROOT 和 GOPATH 的区别是什么？', 'GOROOT 是 Go 安装目录，包含 Go 标准库和编译器；GOPATH 是工作区目录，包含第三方依赖和用户代码（Go modules 模式下主要用于缓存等）。Go modules 模式（1.16+）下 GOPATH 不再是编译必需。', '["GOROOT", "GOPATH", "Go 安装", "工作区"]', '["提示1: GOROOT 安装位置", "提示2: Go modules 后 GOPATH 弱化"]', '["环境", "配置"]', 'official'),
(68, 3, 1, 'GO111MODULE', 'GO111MODULE 环境变量的作用和取值是什么？', 'GO111MODULE 控制是否启用 Go Modules：off（禁用，使用 GOPATH 模式）、on（强制启用）、auto（自动判断，项目中有 go.mod 文件则启用）。Go 1.16+ 默认 auto，Go 1.17+ 不再支持 GOPATH 模式。', '["GO111MODULE", "Go Modules", "环境变量"]', '["提示1: auto 根据 go.mod 自动判断", "提示2: Go 1.16+ 默认 auto"]', '["模块", "环境变量"]', 'official'),
(69, 3, 1, '性能基础', 'Go 中如何测量代码性能？pprof 的基本用法是什么？', '使用 testing.B 基准测试和 pprof 性能分析。引入 _ "net/http/pprof" 后通过 /debug/pprof/ 端点获取 profile。常用：go tool pprof http://localhost:6060/debug/pprof/heap 分析堆内存，go tool pprof .../pprof/cpu 分析 CPU。', '["pprof", "基准测试", "性能分析", "net/http/pprof"]', '["提示1: testing.B 用于基准测试", "提示2: /debug/pprof/ 提供多种 profile"]', '["性能", "pprof", "工具"]', 'official'),
(70, 3, 1, '编译命令', 'go build 的常用参数有哪些？', '常用参数：-o 指定输出文件名；-race 启用竞态检测；-tags 指定编译标签；-ldflags 传递链接器参数（设置版本号等）；-gcflags 传递编译器参数；-v 显示编译包名；-a 强制重新编译所有依赖。', '["go build", "编译参数", "-ldflags", "-gcflags"]', '["提示1: -ldflags 用于设置版本信息", "提示2: -race 启用竞态检测"]', '["编译", "构建", "工具链"]', 'official'),
(71, 3, 1, '交叉编译', 'Go 如何实现交叉编译？', '通过设置 GOOS 和 GOARCH 环境变量实现交叉编译。例如：GOOS=linux GOARCH=amd64 go build 编译 Linux amd64 可执行文件。Go 有出色的交叉编译支持，无需额外工具链即可跨平台编译。', '["交叉编译", "GOOS", "GOARCH", "跨平台"]', '["提示1: 设置 GOOS 为目标操作系统", "提示2: 设置 GOARCH 为目标架构"]', '["编译", "交叉编译"]', 'official'),

-- L2 初级 (ID 72-78)
(72, 3, 2, 'GC 触发', 'Go 垃圾回收的触发条件有哪些？', 'GC 触发条件：1）内存分配达到阈值（GOGC 比例，默认 100%，即堆大小翻倍时触发）；2）定时触发（默认 2 分钟无 GC 会强制触发）；3）手动触发 runtime.GC()；4）通过 runtime/gctrace 设置可查看 GC 日志。', '["GC 触发", "GOGC", "runtime.GC", "gctrace"]', '["提示1: GOGC 控制堆增长比例", "提示2: 2 分钟无 GC 会强制触发"]', '["GC", "内存管理", "运行时"]', 'official'),
(73, 3, 2, 'GOGC', 'GOGC 环境变量的作用是什么？如何通过它优化 GC 延迟？', 'GOGC 定义触发 GC 的堆增长百分比，默认 100。例如 GOGC=200 表示堆增长到原大小的 200% 才触发 GC，减少 GC 频率但增加内存使用。调优思路：降低 GOGC 减少延迟峰值，增加 GOGC 提高吞吐量。GOGC=off 关闭 GC。', '["GOGC", "GC 调优", "堆增长", "延迟优化"]', '["提示1: 降低 GOGC 减少延迟峰值", "提示2: GOGC=off 关闭 GC"]', '["GC", "调优", "环境变量"]', 'official'),
(74, 3, 2, '内存统计', '如何获取 Go 程序运行时的内存统计信息？', '通过 runtime.ReadMemStats 函数获取 runtime.MemStats 结构体，包含分配字节数（Alloc/TotalAlloc）、堆对象数（HeapObjects）、GC 暂停时间（PauseNs）等。也可通过 pprof 堆分析或 expvar 暴露统计。', '["runtime.ReadMemStats", "MemStats", "内存统计", "HeapAlloc"]', '["提示1: Alloc 是当前分配的字节数", "提示2: PauseNs 记录 GC 暂停时间"]', '["内存", "运行时", "监控"]', 'official'),
(75, 3, 2, '数据竞争检测', 'Go 的 -race 检测原理是什么？对性能有何影响？', 'race detector 基于 ThreadSanitizer（C/C++ 工具），在编译时插入额外的内存访问检测代码。运行时检测所有内存访问并报告未同步的并发访问。性能影响：CPU 增加 2-20 倍，内存增加 5-10 倍。', '["race detector", "ThreadSanitizer", "数据竞争", "性能影响"]', '["提示1: 基于 ThreadSanitizer 技术", "提示2: 性能开销较大"]', '["调试", "竞态检测", "工具"]', 'official'),
(76, 3, 2, 'trace 工具', 'go tool trace 的用途是什么？如何生成 trace 文件？', 'go tool trace 可视化展示 goroutine 调度、GC、网络 IO 等事件的时间线。使用方式：1）代码中调用 trace.Start(f) 和 trace.Stop()；2）运行生成 trace.out；3）执行 go tool trace trace.out 在浏览器查看。', '["go tool trace", "trace", "调度可视化", "性能分析"]', '["提示1: trace 提供时间线视图", "提示2: 可查看 goroutine 调度细节"]', '["性能分析", "trace", "工具"]', 'official'),
(77, 3, 2, 'GODEBUG', 'GODEBUG 环境变量有哪些常用选项？', 'GODEBUG 提供运行时诊断：gctrace=1 打印 GC 日志；schedtrace=X 每隔 X 毫秒打印调度信息；scheddetail=1 打印详细调度信息；inittrace=1 打印 init 函数执行时间；allocfreetrace=1 打印内存分配释放。', '["GODEBUG", "gctrace", "schedtrace", "运行时调试"]', '["提示1: gctrace=1 查看 GC 详情", "提示2: schedtrace 查看调度信息"]', '["调试", "运行时", "环境变量"]', 'official'),
(78, 3, 2, '构建约束', 'Go 中构建约束（build constraints）如何使用？', '构建约束通过源码注释控制哪些文件参与编译。有两种形式：1）//go:build linux,amd64（Go 1.17+ 推荐）；2）// +build linux（旧式）。支持逻辑运算符 && || !，用于条件编译和平台适配。', '["build constraints", "//go:build", "条件编译", "构建标签"]', '["提示1: go:build 是推荐的新语法", "提示2: 与 GOOS/GOARCH 结合使用"]', '["编译", "构建约束"]', 'official'),

-- L3 中级 (ID 79-85)
(79, 3, 3, 'GC 调优', '如何优化 Go 程序的 GC 性能？', 'GC 优化策略：1）调整 GOGC 减少 GC 频率；2）复用对象减少分配（sync.Pool、对象池）；3）预分配 slice/map 容量减少扩容分配；4）减少指针使用（指针越多 GC 扫描越慢）；5）使用 pprof 定位高分配代码路径。', '["GC 优化", "对象池", "sync.Pool", "预分配"]', '["提示1: sync.Pool 复用临时对象", "提示2: 减少指针能降低 GC 压力"]', '["GC", "性能优化", "内存管理"]', 'official'),
(80, 3, 3, '逃逸分析', 'Go 中逃逸分析的实现机制是什么？哪些情况会导致变量逃逸？', '逃逸分析在编译时进行，编译器跟踪变量引用。导致逃逸的常见情况：1）返回局部变量指针；2）变量被全局变量引用；3）变量被已逃逸的变量引用；4）接口类型的方法调用（动态分发）；5）变量大小不确定（如 slice 扩容）；6）闭包引用外部变量。', '["逃逸分析", "逃逸条件", "编译器分析", "闭包逃逸"]', '["提示1: 返回局部指针会逃逸", "提示2: 接口调用可能导致逃逸"]', '["逃逸分析", "编译器", "性能"]', 'official'),
(81, 3, 3, 'sync.Pool', 'sync.Pool 的实现原理和正确使用方法是什么？', 'sync.Pool 维护临时对象池，用于缓存和复用频繁分配的对象。每个 P 有本地缓存（私有+共享池），Get 优先从本地获取，Put 放回本地。GC 时会清空 Pool，不能用于持久化状态。适用于高频分配释放的场景如 JSON 解析。', '["sync.Pool", "对象池", "临时对象", "GC"]', '["提示1: GC 时会清空 Pool", "提示2: 每个 P 有本地缓存"]', '["对象池", "性能优化", "GC"]', 'official'),
(82, 3, 3, '边界检查', 'Go 中边界检查消除（BCE）的优化原理是什么？', '边界检查消除是编译器在索引操作时，如果能在编译期确定索引在范围内，则删除运行时边界检查代码。通过为编译器提供足够的信息（如提前检查长度、使用恒等约束），减少不必要的边界判断，提升性能。', '["BCE", "边界检查消除", "编译器优化", "安全性"]', '["提示1: 编译期确定的索引不检查", "提示2: 手动提供长度信息辅助优化"]', '["编译器", "性能优化", "安全"]', 'official'),
(83, 3, 3, '内联优化', 'Go 编译器函数内联的策略和限制是什么？', '内联将小函数的代码直接嵌入调用处，减少函数调用开销。内联策略：复杂度低的短函数被内联；递归函数不内联；闭包和 interface 调用通常不内联。可用 -gcflags="-m" 查看内联决策，//go:noinline 禁止内联。', '["内联", "函数内联", "编译器优化", "-gcflags"]', '["提示1: 短函数更容易被内联", "提示2: 递归函数不内联"]', '["编译器", "性能优化", "内联"]', 'official'),
(84, 3, 3, '栈扩容', 'Go 运行时 goroutine 栈的动态扩缩容机制是什么？', 'goroutine 初始栈约 2KB，当栈空间不足时触发栈扩容（栈拷贝，stack copying），将栈移动到更大的内存空间（约翻倍）。当栈使用率低时可能触发缩容。栈拷贝涉及指针更新，由运行时自动处理，对用户透明。', '["栈扩容", "栈拷贝", "goroutine 栈", "动态栈"]', '["提示1: 初始栈约 2KB", "提示2: 栈扩缩容对用户透明"]', '["运行时", "栈管理", "goroutine"]', 'official'),
(85, 3, 3, '内存分配器', 'Go 内存分配器（mcache/mcentral/mheap）的层次结构是什么？', 'Go 使用分层内存分配器，类似 tcmalloc：1）mcache：每个 P 的本地缓存，无需锁即可分配小对象；2）mcentral：中心缓存，为 mcache 提供对象，需要锁；3）mheap：堆的全局管理，管理 span 和大对象分配。大对象（>32KB）直接从 mheap 分配。', '["mcache", "mcentral", "mheap", "内存分配器"]', '["提示1: mcache 无锁分配", "提示2: 大对象直接从 mheap 分配"]', '["内存管理", "分配器", "运行时"]', 'official'),

-- L4 高级 (ID 86-92)
(86, 3, 4, '写屏障', 'Go GC 中写屏障（write barrier）的作用和原理是什么？', '写屏障是 GC 中保证并发标记正确性的机制。Go 使用混合写屏障（混合了 Dijkstra 插入屏障和 Yuasa 删除屏障），在修改指针时记录引用关系变化。编译器在每次指针写入时插入写屏障代码，用于通知 GC 标记阶段指针变更。', '["写屏障", "混合写屏障", "并发 GC", "标记正确性"]', '["提示1: 写屏障记录指针变更", "提示2: 插入和删除屏障结合使用"]', '["GC", "并发标记", "运行时"]', 'official'),
(87, 3, 4, 'GC 暂停', 'Go GC 的 STW（Stop The World）阶段有哪些？如何优化？', 'Go GC 主要有四个阶段：1）标记准备（STW，启动写屏障）；2）并发标记（非 STW）；3）标记终止（STW，关闭写屏障）；4）清除（非 STW）。1.8+ 后 STW 时间已大幅缩短（通常在微秒到毫秒级）。优化：调整 GOGC、减少对象分配。', '["STW", "GC 阶段", "暂停时间", "并发标记"]', '["提示1: Go 1.8+ 大幅减少 STW", "提示2: 标记准备和标记终止有短暂 STW"]', '["GC", "STW", "延迟优化"]', 'official'),
(88, 3, 4, '调度跟踪', '如何通过调度跟踪发现性能瓶颈？', '使用 go tool trace 和 GODEBUG=schedtrace=100 分析调度行为。关注指标：Goroutine 数量（大量 goroutine 可能竞争 P）、线程数量（M 过多增加调度开销）、Syscall 频次（频繁系统调用导致 P 解绑重绑定）。定位 P 空闲和 goroutine 阻塞的热点。', '["调度跟踪", "schedtrace", "go tool trace"]', '["提示1: 关注 goroutine 数量异常", "提示2: syscall 频繁影响调度效率"]', '["调度", "性能分析"]', 'official'),
(89, 3, 4, '内存火焰图', '如何分析和优化 Go 程序的内存分配热点？', '使用 pprof 生成内存 profile：go tool pprof -http=:8080 http://.../debug/pprof/heap。关注 flat/inuse 值高的函数。使用 alloc_objects 和 alloc_space 模式定位分配次数和大小。优化方向：复用对象（sync.Pool）、预分配容量、避免临时字符串拼接。', '["pprof", "内存火焰图", "分配热点", "alloc_objects"]', '["提示1: alloc_objects 看分配次数", "提示2: alloc_space 看分配大小"]', '["性能分析", "pprof", "内存", "优化"]', 'official'),
(90, 3, 4, '编译优化', 'Go 编译器 SSA（静态单赋值）后端做了哪些优化？', 'Go 编译器 SSA 后端在 IR（中间表示）上执行多趟优化：死代码消除、冗余边界检查消除、常量折叠与传播、循环优化（如循环不变量外提）、指令选择与寄存器分配、无用的 store 消除等。这些优化显著提升了生成代码的质量。', '["SSA", "编译器优化", "中间表示", "死代码消除"]', '["提示1: SSA 是编译器后端优化框架", "提示2: 循环不变量外提是重要优化"]', '["编译器", "SSA", "优化"]', 'official'),
(91, 3, 4, 'P 数量', 'GOMAXPROCS 的作用是什么？设置不当有什么影响？', 'GOMAXPROCS 限制 P 的最大数量，默认等于 CPU 逻辑核数。P 太少导致并发能力不足，CPU 利用率低；P 太多增加调度和内存开销（每个 P 有本地队列、mcache 等）。在容器环境中需注意 cgroup 限制，使用 uber-go/automaxprocs 自动适配。', '["GOMAXPROCS", "P 数量", "容器", "CPU"]', '["提示1: 默认值为 CPU 核数", "提示2: 容器中需适配 cgroup"]', '["调度", "GOMAXPROCS", "容器"]', 'official'),
(92, 3, 4, '调试技巧', 'Go 程序有 core dump 如何调试？Delve 调试器的使用技巧？', 'core dump 调试：设置 GOTRACEBACK=crash/cores 生成 core 文件，使用 delve 的 core 子命令加载：dlv core ./binary core.dump。Delve 技巧：break 设置断点、goroutines 查看所有 goroutine、stack 查看调用栈、locals 查看局部变量、condition 条件断点。', '["Delve", "core dump", "GOTRACEBACK", "调试"]', '["提示1: GOTRACEBACK=crash 生成 core", "提示2: dlv core 加载 core dump 调试"]', '["调试", "Delve", "排错"]', 'official'),

-- ====================================================================
-- 领域 4: 工程实践 (ID 93-116)
-- L1 入门 (ID 93-98)
-- ====================================================================
(93, 4, 1, '包管理', 'Go modules 中 go.mod 文件的结构和常用指令是什么？', 'go.mod 包含模块名、Go 版本和依赖列表。常用指令：require（声明依赖及版本）、replace（替换依赖路径）、exclude（排除依赖版本）、retract（撤回版本）。go.sum 记录依赖的哈希值用于验证。', '["go.mod", "Go Modules", "require", "replace"]', '["提示1: replace 用于本地替换依赖", "提示2: go.sum 记录哈希校验"]', '["模块", "依赖管理", "构建"]', 'official'),
(94, 4, 1, 'go get', 'go get 命令的用法和 go install 的区别是什么？', 'go get 用于管理 go.mod 中的依赖（1.18+ 不再自动构建安装），go install 用于编译安装可执行文件到 $GOPATH/bin。推荐做法：go get @version 更新依赖，go install pkg@version 安装工具。', '["go get", "go install", "依赖管理", "工具安装"]', '["提示1: go get 管理依赖", "提示2: go install 安装可执行文件"]', '["模块", "命令"]', 'official'),
(95, 4, 1, '测试基础', 'Go 中 testing 包的基本用法和命名规则是什么？', '测试文件以 _test.go 结尾，测试函数以 TestXxx 命名（参数 *testing.T）。子测试用 t.Run(name, fn)。Benchmark 函数以 BenchmarkXxx 命名（参数 *testing.B）。示例函数以 ExampleXxx 命名。', '["testing", "Test", "Benchmark", "Example"]', '["提示1: 测试文件以 _test.go 结尾", "提示2: 使用 t.Run 创建子测试"]', '["测试", "testing"]', 'official'),
(96, 4, 1, '代码格式', 'Go 的代码格式化工具 gofmt 有什么特点？', 'gofmt 强制执行 Go 官方代码风格（制表符缩进、特定括号位置等），不可配置。自动格式化包括：缩进、对齐、移除多余空行、调整导入分组。go fmt 命令包装了 gofmt。使用 goimports 还会自动管理 import 语句。', '["gofmt", "代码风格", "格式化", "goimports"]', '["提示1: gofmt 风格不可配置", "提示2: goimports 自动管理 import"]', '["工具", "代码风格", "格式化"]', 'official'),
(97, 4, 1, 'go vet', 'go vet 命令的作用是什么？能检测哪些问题？', 'go vet 对 Go 源码进行静态分析，检测可疑构造。可检测：错误格式的 Printf 调用、无效的锁复制、未使用的变量、死代码、错误的 build 标签、闭包陷阱等。是 CI 中重要的代码质量检查工具。', '["go vet", "静态分析", "代码质量", "CI"]', '["提示1: 检测 Printf 格式错误", "提示2: 可检测锁的值传递"]', '["静态分析", "工具", "代码质量"]', 'official'),
(98, 4, 1, '文档生成', 'Go 中如何编写文档注释？godoc 的规范是什么？', 'Go 文档注释使用 // 放在声明前，格式类似 godoc 规范：第一句是被注释内容的摘要（以名称开头），之后是详细说明。示例代码放在 Example 函数中。可用 go doc 命令查看文档，pkg.go.dev 托管包文档。', '["godoc", "文档注释", "go doc", "示例代码"]', '["提示1: 第一句应该是摘要", "提示2: Example 函数作为示例代码"]', '["文档", "规范"]', 'official'),

-- L2 初级 (ID 99-104)
(99, 4, 2, '表驱动测试', 'Go 中如何编写表驱动测试（table-driven tests）？', '表驱动测试定义测试用例切片，每个用例包含输入和期望输出结构体。通过 for range 遍历用例执行测试，使用 t.Run 创建子测试。优势：易于添加新用例、统一的测试逻辑、清晰展示边界条件。', '["表驱动测试", "table-driven", "子测试", "测试用例"]', '["提示1: 定义测试用例结构体切片", "提示2: 每个用例可独立运行"]', '["测试", "最佳实践"]', 'official'),
(100, 4, 2, '测试覆盖', '如何计算和查看 Go 测试覆盖率？', '使用 go test -cover 计算覆盖率，-coverprofile 输出覆盖文件，go tool cover -html=file 生成 HTML 报告可视化。也可用 -covermode 设置模式（set/count/atomic）。原子模式用于并发测试的覆盖率统计。', '["测试覆盖", "cover", "覆盖率报告", "go tool cover"]', '["提示1: -coverprofile 输出覆盖文件", "提示2: cover -html 可视化报告"]', '["测试", "覆盖率"]', 'official'),
(101, 4, 2, '依赖管理', 'Go modules 中如何处理依赖版本升级和冲突？', '使用 go list -u -m all 查看可升级版本。go get pkg@version 升级特定依赖，go get -u 升级所有依赖。go mod tidy 清理无用依赖。版本冲突通过 go.mod 中的最小版本选择算法解决，每个依赖使用所需的最高最小版本。', '["go mod tidy", "版本升级", "最小版本选择", "依赖冲突"]', '["提示1: go mod tidy 清理无用的依赖", "提示2: 最小版本选择解决冲突"]', '["依赖管理", "模块", "版本"]', 'official'),
(102, 4, 2, 'vendor', 'Go modules 中 vendor 目录的作用是什么？何时使用？', 'vendor 目录存放依赖的副本，go mod vendor 生成。使用 go build -mod=vendor 或设置 GOFLAGS=-mod=vendor 启用。适用场景：离线环境、确保构建可复现、CI/CD 中避免下载依赖、依赖源不稳定时。', '["vendor", "离线构建", "可复现", "依赖缓存"]', '["提示1: go mod vendor 生成 vendor", "提示2: -mod=vendor 启用 vendor 模式"]', '["构建", "依赖管理"]', 'official'),
(103, 4, 2, 'mock', 'Go 中如何进行 mock 测试？常用 mock 工具有哪些？', 'Go 中 mock 通过接口实现：定义接口，生产类和 mock 类分别实现。常用工具：gomock（代码生成）、testify/mock（运行时断言）、monkey 补丁（不建议用于生产）。Go 1.14+ 的 go:generate 可自动生成 mock 代码。', '["mock", "gomock", "testify", "接口 mock"]', '["提示1: mock 必须基于接口", "提示2: go:generate 可自动生成 mock"]', '["测试", "mock", "工具"]', 'official'),
(104, 4, 2, 'fuzz', 'Go 1.18 的 fuzz 测试如何使用？', 'fuzz 测试使用 testing.F 类型，F.Fuzz 方法注册模糊测试函数。go test -fuzz=FuzzFunc 运行模糊测试。F.Add 添加种子语料库。Go 编译器会自动检测并修复发现的崩溃和边界情况。模糊测试适合发现安全漏洞和边界条件错误。', '["fuzz", "模糊测试", "testing.F", "种子语料"]', '["提示1: F.Fuzz 注册测试函数", "提示2: -fuzz 标志运行模糊测试"]', '["测试", "fuzz"]', 'official'),

-- L3 中级 (ID 105-110)
(105, 4, 3, '单元测试', '如何编写高质量的 Go 单元测试？有哪些最佳实践？', '最佳实践包括：1）使用表驱动测试覆盖边界条件；2）使用 t.Helper() 标记辅助函数；3）使用 t.Cleanup() 清理资源；4）使用 testify/assert 进行断言；5）mock 外部依赖；6）保持测试独立可重复；7）关注核心逻辑而非实现细节。', '["单元测试", "t.Helper", "t.Cleanup", "testify"]', '["提示1: t.Helper 标记辅助函数", "提示2: t.Cleanup 注册清理函数"]', '["测试", "最佳实践", "质量"]', 'official'),
(106, 4, 3, '性能测试', 'Go 中如何编写准确的基准测试？需要注意什么？', '使用 testing.B 编写基准测试，b.N 由框架自动调整。注意事项：1）ResetTimer 排除初始化耗时；2）RunParallel 测试并发性能；3）避免编译器优化掉被测代码（赋值给包级变量）；4）StopTimer/StartTimer 排除无关操作。', '["基准测试", "testing.B", "ResetTimer", "RunParallel"]', '["提示1: 使用包级变量防止优化", "提示2: RunParallel 测试并发性能"]', '["测试", "基准测试", "性能"]', 'official'),
(107, 4, 3, 'go generate', 'go generate 命令的用途和使用方式是什么？', 'go generate 扫描源码中的 //go:generate 指令并执行。常用场景：生成 protobuf 代码（protoc）、生成 mock 代码（gomock）、生成 stringer 方法、嵌入静态资源（statik）。每条指令以 //go:generate command args 格式编写。', '["go generate", "//go:generate", "代码生成", "protoc"]', '["提示1: 在源码注释中写生成指令", "提示2: 常用于 protobuf 和 mock 生成"]', '["代码生成", "工具", "构建"]', 'official'),
(108, 4, 3, 'CI/CD', 'Go 项目 CI/CD 中应包含哪些质量检查步骤？', '推荐步骤：1）go vet 静态分析；2）golangci-lint 综合 lint（包含 errcheck、gosimple 等）；3）go test -race 带竞态检测的测试；4）go test -cover 检查覆盖率；5）go build 确认编译通过；6）go mod tidy 和 go mod verify 检查依赖完整性。', '["CI/CD", "golangci-lint", "go vet", "持续集成"]', '["提示1: golangci-lint 整合多种 linter", "提示2: go mod verify 验证依赖完整性"]', '["CI/CD", "质量", "工程实践"]', 'official'),
(109, 4, 3, '依赖注入', 'Go 中如何实现依赖注入？有哪些常用框架？', '依赖注入通过将依赖作为参数传入而非在内部创建，降低耦合。实现方式：1）手动注入（构造函数参数）；2）Google Wire（编译期注入，代码生成）；3）Uber dig（运行时反射注入）；4）Facebook inject。推荐 Wire，编译期检查保证类型安全。', '["依赖注入", "Wire", "dig", "构造函数"]', '["提示1: Wire 是编译期注入", "提示2: dig 是运行时反射注入"]', '["设计模式", "依赖注入"]', 'official'),
(110, 4, 3, '接口设计', 'Go 中好的接口设计原则是什么？', 'Go 接口设计原则：1）小而精（推荐 1-3 个方法，如 io.Reader/Writer）；2）定义在消费者包而非生产者包；3）接受接口返回结构体（接受抽象，返回具体）；4）接口名加 -er 后缀（如 Reader、Formatter）；5）避免提前抽象，有需要时再提取接口。', '["接口设计", "小接口", "接口隔离", "设计原则"]', '["提示1: 接口应小而精", "提示2: 定义在消费者包"]', '["接口", "设计原则", "最佳实践"]', 'official'),

-- L4 高级 (ID 111-116)
(111, 4, 4, '错误处理策略', 'Go 中如何实现优雅的错误处理？有哪些高级模式？', '高级错误处理模式：1）自定义错误类型实现更多上下文（实现 Unwrap 方法支持 errors.Is/As）；2）使用 errors.Join 合并多个错误；3）使用 fmt.Errorf + %w 包装错误链；4）使用 panic/recover 处理真正异常情况；5）使用 golang.org/x/xerrors 提供更丰富的错误信息。', '["错误包装", "errors.Is", "errors.As", "%w"]', '["提示1: %w 包装错误支持 Unwrap", "提示2: errors.Is 检查错误链"]', '["错误处理", "高级", "模式"]', 'official'),
(112, 4, 4, '代码组织', 'Go 项目推荐的项目布局（project layout）是什么？', 'Go 推荐的标准项目布局包括：cmd/（可执行文件入口）、internal/（私有包）、pkg/（可导出的库代码）、api/（API 定义）、configs/（配置文件）、scripts/（脚本）、test/（集成测试）。internal 目录下的包不能被外部导入。', '["项目布局", "cmd", "internal", "pkg"]', '["提示1: internal 目录对外不可见", "提示2: cmd 存放 main 入口文件"]', '["项目结构", "工程实践"]', 'official'),
(113, 4, 4, '语义化版本', 'Go modules 中语义化版本和兼容性规则是什么？', '遵循 semver 规范：vMAJOR.MINOR.PATCH。MAJOR 版本不兼容 API 变更时增加；MINOR 版本向后兼容新增功能时增加；PATCH 版本向后兼容的 bug 修复时增加。Go modules 要求 v2+ 版本在模块路径后加 /v2，通过 go.mod 中的 major version bump 管理兼容性。', '["语义化版本", "semver", "兼容性", "v2"]', '["提示1: v2+ 版本需要 /v2 路径后缀", "提示2: MAJOR 变更表示不兼容"]', '["版本管理", "语义化", "模块"]', 'official'),
(114, 4, 4, '代码评审', 'Go 代码评审中应重点关注哪些方面？', '评审重点：1）错误处理是否正确（err 是否被检查）；2）defer 使用是否恰当（资源释放）；3）并发安全（数据竞态、锁使用）；4）接口设计是否合理；5）性能考量（不必要的分配、逃逸）；6）测试覆盖是否充分；7）命名和代码风格是否符合 Go 惯例。', '["代码评审", "code review", "质量检查", "最佳实践"]', '["提示1: 关注错误是否被检查", "提示2: 关注并发安全问题"]', '["代码评审", "质量", "工程实践"]', 'official'),
(115, 4, 4, '热加载', 'Go 中如何实现开发环境的热重载？原理是什么？', '热重载工具（如 Air、Fresh）监听文件变化，自动重新编译并重启程序。原理：使用 fsnotify 监听文件系统事件，检测到变更后发送 SIGINT 终止旧进程，编译新二进制并启动。无法像解释型语言那样实现真正的热替换。', '["热重载", "Air", "fsnotify", "文件监听"]', '["提示1: Go 热重载本质是重启进程", "提示2: Air 是常用的热重载工具"]', '["开发工具", "热重载"]', 'official'),
(116, 4, 4, '安全实践', 'Go 程序中常见的安全漏洞和防范措施有哪些？', '常见安全漏洞：1）SQL 注入（使用参数化查询）；2）XSS（输出转义）；3）命令注入（避免 shell 调用）；4）不安全的反序列化；5）敏感信息泄露（硬编码密钥）。防范：使用安全库、输入验证、最小权限原则、依赖漏洞扫描（govulncheck）。', '["安全", "SQL 注入", "govulncheck", "输入验证"]', '["提示1: 使用参数化查询防 SQL 注入", "提示2: govulncheck 扫描依赖漏洞"]', '["安全", "最佳实践", "漏洞"]', 'official'),

-- ====================================================================
-- 领域 5: 微服务与 RPC (ID 117-144)
-- L1 入门 (ID 117-123)
-- ====================================================================
(117, 5, 1, 'RPC 基础', '什么是 RPC？Go 中如何实现简单的 RPC 调用？', 'RPC（远程过程调用）允许程序调用远程服务像调用本地函数一样。Go 标准库 net/rpc 提供基础 RPC 实现，定义服务方法（需满足签名约束），通过 TCP/HTTP 传输。更常用的是 gRPC，基于 protobuf 的高性能 RPC 框架。', '["RPC", "远程调用", "net/rpc", "gRPC"]', '["提示1: RPC 屏蔽网络通信细节", "提示2: gRPC 是主流 RPC 框架"]', '["RPC", "微服务", "通信"]', 'official'),
(118, 5, 1, 'HTTP 服务', 'Go 中如何创建 HTTP 服务？标准库 net/http 的基本用法。', '使用 http.HandleFunc 注册路由，http.ListenAndServe 启动服务。也可使用 http.Server 结构体自定义配置。支持中间件模式（Handler 包装）。常用框架有 Gin、Echo、Fiber 等，但标准库也足够构建生产级服务。', '["net/http", "HTTP 服务", "路由", "中间件"]', '["提示1: HandleFunc 注册路由", "提示2: 标准库已支持大部分需求"]', '["HTTP", "Web", "服务"]', 'official'),
(119, 5, 1, 'JSON 序列化', 'Go 中 JSON 序列化和反序列化如何使用？', '使用 encoding/json 包：json.Marshal(v) 序列化，json.Unmarshal(data, &v) 反序列化。通过结构体标签 json:"field_name" 控制字段映射。支持 omitempty 忽略零值字段，string 标签将数字转字符串。MarshalIndent 输出格式化的 JSON。', '["JSON", "Marshal", "Unmarshal", "json tag"]', '["提示1: 结构体标签控制映射", "提示2: omitempty 忽略零值字段"]', '["JSON", "序列化", "编码"]', 'official'),
(120, 5, 1, 'API 设计', 'RESTful API 设计的基本原则是什么？', 'RESTful API 原则：1）资源导向 URL（/users/:id）；2）使用 HTTP 方法表示操作（GET 查、POST 创、PUT 改、DELETE 删）；3）无状态通信；4）使用 HTTP 状态码表示结果；5）支持分页、过滤、排序等查询参数；6）版本管理（/v1/）。', '["RESTful", "API 设计", "HTTP 方法", "状态码"]', '["提示1: URL 表示资源，方法表示操作", "提示2: 使用合适的 HTTP 状态码"]', '["API", "RESTful", "设计"]', 'official'),
(121, 5, 1, 'Protobuf 基础', 'Protocol Buffers 是什么？Go 中如何使用？', 'Protobuf 是 Google 的高效结构化数据序列化协议，通过 .proto 文件定义消息格式，生成各语言代码。Go 中使用 protoc 编译器和 protoc-gen-go 插件生成 .pb.go 文件。比 JSON 更小更快，适合内部服务通信。', '["Protobuf", "protoc", "序列化", ".proto"]', '["提示1: protoc 编译器生成代码", "提示2: protobuf 比 JSON 更高效"]', '["Protobuf", "序列化", "RPC"]', 'official'),
(122, 5, 1, '服务注册', '什么是服务注册与发现？基本工作原理是什么？', '服务注册与发现管理微服务实例的地址信息。服务启动时注册自身到注册中心（如 Consul、etcd、Nacos），下线时注销。客户端从注册中心获取可用服务列表，实现负载均衡和故障转移。心跳机制检测服务健康状态。', '["服务注册", "服务发现", "Consul", "etcd"]', '["提示1: 注册中心维护服务地址", "提示2: 心跳检测健康状态"]', '["微服务", "服务发现", "注册中心"]', 'official'),
(123, 5, 1, 'API 网关', 'API 网关在微服务中的作用是什么？', 'API 网关是微服务的统一入口，功能包括：请求路由、负载均衡、认证授权、限流熔断、日志监控、协议转换、聚合多个后端服务。减轻客户端复杂度，集中处理横切关注点。常见实现：Kong、APISIX、Spring Cloud Gateway 等。', '["API 网关", "路由", "限流", "认证"]', '["提示1: API 网关是统一入口", "提示2: 处理横切关注点"]', '["API 网关", "微服务", "架构"]', 'official'),

-- L2 初级 (ID 124-130)
(124, 5, 2, 'gRPC 基础', 'gRPC 的核心特性和优点是什么？', 'gRPC 是基于 HTTP/2 的高性能 RPC 框架，核心特性：1）基于 protobuf 的二进制序列化；2）支持四种调用模式：一元、服务端流、客户端流、双向流；3）基于 HTTP/2 的多路复用和头部压缩；4）内置认证、负载均衡、健康检查。', '["gRPC", "HTTP/2", "protobuf", "流式调用"]', '["提示1: gRPC 使用 HTTP/2 协议", "提示2: 支持四种调用模式"]', '["gRPC", "RPC", "通信"]', 'official'),
(125, 5, 2, 'gRPC 拦截器', 'gRPC 拦截器（interceptor）的用途和实现方式是什么？', 'gRPC 拦截器类似于 HTTP 中间件，在 RPC 调用前后执行逻辑。一元拦截器处理普通 RPC，流拦截器处理流式 RPC。用于统一日志、鉴权、监控、错误处理。通过实现 UnaryServerInterceptor 和 StreamServerInterceptor 接口。', '["gRPC 拦截器", "中间件", "UnaryServerInterceptor", "鉴权"]', '["提示1: 一元和流式两种拦截器", "提示2: 用于横切关注点"]', '["gRPC", "中间件", "拦截器"]', 'official'),
(126, 5, 2, 'protobuf 进阶', 'protobuf 中 oneof、map、enum 等高级类型如何定义？', 'oneof 定义互斥字段集合（使用 oneof 关键字）；map<KeyType, ValueType> 定义映射类型；enum 定义枚举，首个枚举值必须为 0。高级特性：import 导入其他 proto、package 避免命名冲突、option go_package 指定生成包路径。', '["oneof", "map", "enum", "go_package"]', '["提示1: oneof 字段互斥", "提示2: 枚举首值必须为 0"]', '["Protobuf", "类型系统"]', 'official'),
(127, 5, 2, 'HTTP 中间件', 'Go 中如何编写 HTTP 中间件？', 'HTTP 中间件是一个接收 http.Handler 并返回 http.Handler 的函数。通过装饰器模式实现：func middleware(next http.Handler) http.Handler { return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) { ...; next.ServeHTTP(w, r) }) }。支持链式组合。', '["中间件", "http.Handler", "装饰器", "链式调用"]', '["提示1: 中间件包装 Handler", "提示2: 支持链式组合"]', '["HTTP", "中间件", "Web"]', 'official'),
(128, 5, 2, '配置管理', 'Go 微服务中如何进行配置管理？推荐哪些工具？', 'Go 配置管理方式：1）环境变量（os.Getenv）；2）配置库如 Viper（支持 YAML/JSON/TOML、远程配置中心）；3）Cleanenv（结构体标签映射环境变量）；4）配置中心（Nacos、etcd、Consul）。推荐 Viper，支持多数据源和热更新。', '["配置管理", "Viper", "环境变量", "配置中心"]', '["提示1: Viper 支持多数据源", "提示2: 推荐使用环境变量+配置库"]', '["配置", "微服务", "工具"]', 'official'),
(129, 5, 2, '健康检查', 'Go 微服务如何实现健康检查端点？', '健康检查通常提供 /healthz 和 /readyz 两个端点：liveness 检查服务是否存活（进程/goroutine），readiness 检查服务是否就绪（依赖资源是否可用）。使用 http.HandleFunc 注册，返回 200 OK 或 503 Service Unavailable。', '["健康检查", "liveness", "readiness", "/healthz"]', '["提示1: liveness 存活检查", "提示2: readiness 就绪检查"]', '["微服务", "健康检查", "运维"]', 'official'),
(130, 5, 2, '优雅启停', 'Go HTTP 服务如何实现优雅关闭？', '使用 http.Server 的 Shutdown(ctx) 方法实现优雅关闭。收到退出信号时：1）停止接收新请求；2）等待正在处理的请求完成（可通过 context.WithTimeout 设置超时）；3）关闭空闲连接；4）释放资源后退出。signal.Notify 捕获系统信号。', '["优雅关闭", "Shutdown", "signal.Notify", "Graceful"]', '["提示1: Shutdown 等待请求完成", "提示2: 使用 signal.Notify 捕获信号"]', '["微服务", "优雅关闭", "运维"]', 'official'),

-- L3 中级 (ID 131-137)
(131, 5, 3, '服务网格', '什么是服务网格（Service Mesh）？Sidecar 模式的原理是什么？', '服务网格是微服务间通信的基础设施层，通过 Sidecar 代理（如 Envoy）拦截所有进出服务的流量，实现服务发现、负载均衡、熔断、可观测性等。Sidecar 与主服务容器同 Pod 部署，对应用透明。Istio 是主流服务网格实现。', '["服务网格", "Sidecar", "Envoy", "Istio"]', '["提示1: Sidecar 代理拦截流量", "提示2: 对应用透明的基础设施层"]', '["服务网格", "Sidecar", "微服务"]', 'official'),
(132, 5, 3, '熔断降级', '熔断器模式在微服务中如何实现？Go 有哪些实现库？', '熔断器模式保护服务免受级联故障影响。三种状态：Closed（正常）、Open（熔断，快速失败）、Half-Open（半开，试探恢复）。Go 实现库：hystrix-go（Netflix Hystrix 移植）、go-resiliency、gobreaker。支持超时、并发控制、错误率阈值等配置。', '["熔断器", "hystrix-go", "gobreaker", "降级"]', '["提示1: 三种状态：Open/Closed/Half-Open", "提示2: 防止级联故障"]', '["熔断", "容错", "微服务"]', 'official'),
(133, 5, 3, '负载均衡', 'gRPC 中负载均衡的策略有哪些？如何配置？', 'gRPC 负载均衡策略：1）round_robin（轮询，默认）；2）pick_first（选择第一个地址）；3）weighted_target（加权负载均衡）；4）ring_hash（一致性哈希）。使用 resolver 组件解析服务地址，balancer 组件分配连接。支持自定义 resolver 和 balancer。', '["gRPC 负载均衡", "round_robin", "一致性哈希", "resolver"]', '["提示1: round_robin 是默认策略", "提示2: 支持自定义 resolver"]', '["负载均衡", "gRPC", "微服务"]', 'official'),
(134, 5, 3, '分布式 tracing', '分布式链路追踪（tracing）的原理是什么？Go 中如何使用 OpenTelemetry？', '分布式 tracing 通过 TraceId 和 SpanId 串联跨服务的请求链路。OpenTelemetry 是 CNCF 的标准。使用：1）初始化 TracerProvider；2）在关键操作创建 Span；3）通过 HTTP/gRPC 头部传播上下文；4）导出到 Jaeger/Zipkin。通过拓扑图和火焰图分析性能瓶颈。', '["分布式追踪", "OpenTelemetry", "TraceId", "Jaeger"]', '["提示1: TraceId 串联跨服务请求", "提示2: OpenTelemetry 是行业标准"]', '["可观测性", "tracing", "微服务"]', 'official'),
(135, 5, 3, '限流', 'Go 中如何实现 API 限流？有哪些常用算法？', '常用限流算法：1）令牌桶（Token Bucket，golang.org/x/time/rate）；2）漏桶（Leaky Bucket，uber-go/ratelimit）；3）滑动窗口；4）计数器。Go 标准库 x/time/rate 提供基于令牌桶的限流器，支持动态速率调整和突发流量控制。', '["限流", "令牌桶", "漏桶", "x/time/rate"]', '["提示1: 令牌桶支持突发流量", "提示2: 漏桶保证请求速率平稳"]', '["限流", "微服务", "保护"]', 'official'),
(136, 5, 3, '重试策略', '微服务中如何设计合理的外调用重试策略？', '重试策略要点：1）指数退避（Exponential Backoff）避免重试风暴；2）加入随机抖动（Jitter）防止惊群效应；3）限定最大重试次数；4）幂等性保证（重试不会造成副作用）；5）仅重试临时错误（如网络超时），非业务错误不重试。', '["重试", "指数退避", "jitter", "幂等性"]', '["提示1: 指数退避+抖动防风暴", "提示2: 仅重试临时错误"]', '["容错", "重试", "微服务"]', 'official'),
(137, 5, 3, '服务版本', '微服务中如何进行 API 版本管理？有哪些策略？', 'API 版本管理策略：1）URL 路径版本（/v1/users，最常用）；2）请求头版本（Accept: application/vnd.company.v1+json）；3）查询参数版本（?version=1）；4）gRPC 使用 protobuf 的向后兼容性。选择 URL 路径版本最简单直接，兼容性最好。', '["API 版本", "版本管理", "向后兼容", "URL 路径"]', '["提示1: URL 路径版本最常用", "提示2: protobuf 天然支持兼容性"]', '["API", "版本管理", "微服务"]', 'official'),

-- L4 高级 (ID 138-144)
(138, 5, 4, '分布式事务', '分布式事务的解决方案有哪些？Go 中如何实现 Saga 模式？', '分布式事务方案：1）2PC/3PC（强一致，性能差）；2）TCC（Try-Confirm-Cancel）；3）Saga（最终一致，通过补偿事务）。Saga 模式通过编排（Choreography）或编排器（Orchestrator）协调多个本地事务。Go 可用 go-saga 或自实现基于消息队列的 Saga。', '["分布式事务", "Saga", "TCC", "最终一致性"]', '["提示1: Saga 是最终一致的", "提示2: 通过补偿事务回滚"]', '["分布式事务", "一致性", "微服务"]', 'official'),
(139, 5, 4, 'Dapr', 'Dapr 是什么？它如何简化微服务开发？', 'Dapr（Distributed Application Runtime）是微软开源的微服务运行时，通过 Sidecar 模式提供构建块 API：服务调用、状态管理、发布订阅、绑定、可观测性等。开发者只需通过 HTTP/gRPC 调用 Dapr API，无需引入特定 SDK，简化了微服务基础设施的集成。', '["Dapr", "Sidecar", "构建块", "运行时"]', '["提示1: Dapr 通过 Sidecar 提供 API", "提示2: 与语言无关的微服务运行时"]', '["Dapr", "微服务", "运行时"]', 'official'),
(140, 5, 4, '流量管理', '微服务中如何实现灰度发布和蓝绿部署？', '灰度发布（金丝雀发布）：将小部分流量导向新版本，逐步增加比例，监控指标确认无误后全量切换。蓝绿部署：维护两套完整环境（蓝=旧版，绿=新版），通过负载均衡一次切换。工具：Envoy 流量权重分配、Istio 虚拟服务规则、Nginx 权重配置。', '["灰度发布", "蓝绿部署", "金丝雀", "流量切换"]', '["提示1: 灰度逐步放量降低风险", "提示2: 蓝绿部署快速回滚"]', '["发布", "流量管理", "运维"]', 'official'),
(141, 5, 4, 'protobuf 兼容', 'protobuf 消息演进时如何保证向后兼容性？', 'protobuf 兼容规则：1）不能修改已有字段编号；2）可以新增字段（老代码忽略未知字段）；3）可以删除字段但需保留字段号（reserved 关键字）；4）更改字段类型需谨慎（不兼容）；5）支持默认值保证新老字段兼容。遵守这些规则可实现无损升级。', '["protobuf 兼容", "reserved", "字段编号", "向后兼容"]', '["提示1: 字段编号一旦分配不可修改", "提示2: reserved 保留已删除字段号"]', '["Protobuf", "兼容性", "协议演进"]', 'official'),
(142, 5, 4, '零信任安全', '零信任架构在微服务中如何落地？', '零信任安全原则：1）所有通信（内网也需认证，mTLS）；2）最小权限原则（RBAC/ABAC）；3）持续验证（每次请求都鉴权）；4）网络微分段。Go 实现：gRPC 的 TLS/mTLS 配置、spiffe/spire 身份认证、OPA 策略引擎、JWT 令牌验证。', '["零信任", "mTLS", "SPIFFE", "OPA"]', '["提示1: 所有通信都需要 mTLS 加密", "提示2: 最小权限原则"]', '["安全", "零信任", "微服务"]', 'official'),
(143, 5, 4, '性能优化', 'gRPC 服务性能调优的关键参数和方法有哪些？', 'gRPC 性能调优：1）调整 MaxRecvMsgSize/MaxSendMsgSize 消息大小限制；2）设置 KeepaliveParams 保持连接活跃；3）配置 InitialWindowSize/InitialConnWindowSize 流控制窗口；4）使用 Protobuf 的字段建议优化消息结构；5）启用 gzip 压缩；6）使用连接池复用连接。', '["gRPC 优化", "流控制", "Keepalive", "连接复用"]', '["提示1: 流控制窗口影响吞吐量", "提示2: 连接池减少握手开销"]', '["gRPC", "性能优化", "调优"]', 'official'),
(144, 5, 4, '事件驱动', '事件驱动架构（EDA）在 Go 微服务中如何实现？', '事件驱动架构通过事件总线异步通信，服务间松耦合。Go 实现：1）使用消息队列（Kafka/RabbitMQ/NATS）发布订阅事件；2）使用 Watermill 库构建事件驱动应用；3）使用 CDC（Change Data Capture）监听数据库变更；4）使用 Outbox 模式保证消息可靠投递。', '["事件驱动", "EDA", "Kafka", "Outbox"]', '["提示1: Outbox 模式保证消息不丢失", "提示2: Watermill 是 Go 的事件驱动库"]', '["事件驱动", "架构", "消息"]', 'official'),

-- ====================================================================
-- 领域 6: 数据与存储 (ID 145-168)
-- L1 入门 (ID 145-150)
-- ====================================================================
(145, 6, 1, 'SQL 基础', 'Go 中 database/sql 包的基本用法是什么？', 'database/sql 提供通用 SQL 接口：sql.Open 打开数据库连接、db.Query 执行查询返回 Rows、db.QueryRow 查询单行、db.Exec 执行无返回的 SQL。使用 Scan 方法将结果映射到变量。需要配合特定数据库驱动（如 go-sql-driver/mysql）使用。', '["database/sql", "sql.Open", "Query", "Scan"]', '["提示1: sql.Open 不建立实际连接", "提示2: Scan 将行映射到变量"]', '["数据库", "SQL", "基础"]', 'official'),
(146, 6, 1, '连接池', 'Go 中如何配置和管理数据库连接池？', '通过 sql.DB 的 SetMaxOpenConns（最大打开连接数）、SetMaxIdleConns（最大空闲连接数）、SetConnMaxLifetime（连接最大存活时间）、SetConnMaxIdleTime（空闲最大时间）配置连接池。合理配置避免连接泄漏和资源耗尽。', '["连接池", "SetMaxOpenConns", "连接泄漏", "sql.DB"]', '["提示1: 最大打开连接数防资源耗尽", "提示2: 连接最大存活时间防断连"]', '["数据库", "连接池", "配置"]', 'official'),
(147, 6, 1, 'CRUD', 'Go 中如何使用 GORM 进行基本的 CRUD 操作？', 'GORM 是流行的 Go ORM 库。创建：db.Create(&user)；查询：db.First(&user, id)、db.Where("name = ?", name).Find(&users)；更新：db.Model(&user).Update("name", "new")；删除：db.Delete(&user)。支持链式调用、自动迁移（AutoMigrate）。', '["GORM", "ORM", "CRUD", "AutoMigrate"]', '["提示1: First 查单条记录", "提示2: AutoMigrate 自动建表"]', '["GORM", "ORM", "数据库"]', 'official'),
(148, 6, 1, 'Redis 基础', 'Go 中如何使用 Redis？go-redis 库的基本用法。', 'go-redis/redis 是 Go 的主流 Redis 客户端。使用：redis.NewClient 创建客户端，支持所有 Redis 命令（Get/Set/HGet/HSet/LPush 等）。支持连接池、哨兵模式、集群模式。使用 context 控制超时和取消。', '["Redis", "go-redis", "缓存", "连接池"]', '["提示1: go-redis 是主流客户端", "提示2: 支持哨兵和集群模式"]', '["Redis", "缓存", "数据存储"]', 'official'),
(149, 6, 1, 'NoSQL', 'Go 中如何操作 MongoDB？官方驱动的基本用法。', 'Go MongoDB 官方驱动（mongo-go-driver）：mongo.Connect 建立连接，collection.Find 查询文档，collection.InsertOne/InsertMany 插入，collection.UpdateOne 更新，collection.DeleteOne 删除。使用 bson.M/bson.D 构建查询条件和文档。', '["MongoDB", "mongo-go-driver", "bson", "NoSQL"]', '["提示1: bson.M 是无序 map", "提示2: bson.D 是有序文档"]', '["MongoDB", "NoSQL", "数据库"]', 'official'),
(150, 6, 1, '事务', 'Go 中如何使用数据库事务？sql.Tx 的基本用法。', '使用 db.Begin() 开启事务返回 *sql.Tx，在 Tx 上执行 SQL 操作，最后 Commit() 提交或 Rollback() 回滚。推荐使用 defer + recover 确保 Rollback。GORM 中通过 db.Transaction(func(tx *gorm.DB) error { ... }) 实现事务。', '["事务", "Begin", "Commit", "Rollback"]', '["提示1: Begin 开启事务", "提示2: defer rollback 防止泄漏"]', '["数据库", "事务", "ACID"]', 'official'),

-- L2 初级 (ID 151-156)
(151, 6, 2, 'GORM 进阶', 'GORM 的关联查询和预加载（Preload）如何使用？', 'GORM 支持 Belongs To、Has One、Has Many、Many To Many 关联。使用 Preload("Orders") 预加载关联数据，Joins 进行 JOIN 查询。关联标签控制外键和引用字段。Preload 带条件：Preload("Orders", "state = ?", "paid")。', '["GORM", "Preload", "关联查询", "JOIN"]', '["提示1: Preload 预加载关联数据", "提示2: Joins 执行 INNER JOIN"]', '["GORM", "ORM", "关联"]', 'official'),
(152, 6, 2, 'SQL 优化', 'Go 中数据库查询优化的一般策略有哪些？', 'SQL 优化策略：1）利用索引（覆盖索引、复合索引最左前缀）；2）减少 N+1 查询（使用 Preload/Join）；3）批量操作（Batch Insert/Update）；4）分页优化（游标分页替代 offset）；5）避免 SELECT *；6）合理使用连接池；7）慢查询日志分析和 EXPLAIN 执行计划。', '["SQL 优化", "索引", "N+1", "游标分页"]', '["提示1: 索引是查询性能的关键", "提示2: N+1 查询需使用预加载"]', '["SQL", "性能优化", "数据库"]', 'official'),
(153, 6, 2, '迁移', 'Go 中如何使用数据库迁移工具管理 schema 变更？', '数据库迁移工具管理 schema 版本变化（类似 Git）。常用工具：golang-migrate/migrate（支持多种数据库）、GORM AutoMigrate（开发环境）、ent（代码生成迁移）。迁移文件通常包含 Up（变更）和 Down（回滚）两部分。', '["数据库迁移", "golang-migrate", "AutoMigrate", "schema"]', '["提示1: 迁移文件包含 Up 和 Down", "提示2: AutoMigrate 适合开发环境"]', '["数据库", "迁移", "工具"]', 'official'),
(154, 6, 2, '缓存策略', 'Go 中常用的缓存模式和缓存策略有哪些？', '常用缓存模式：1）Cache-Aside（旁路缓存，应用程序维护缓存）；2）Read-Through（缓存负责读取）；3）Write-Through（缓存同步写）；4）Write-Behind（异步写回）。策略：TTL 过期、LRU/LFU 淘汰。Go 缓存库：bigcache、freecache、ristretto。', '["缓存", "Cache-Aside", "TTL", "bigcache"]', '["提示1: Cache-Aside 是最常用模式", "提示2: TTL 防止缓存雪崩"]', '["缓存", "策略", "性能"]', 'official'),
(155, 6, 2, '数据一致性', 'Go 中如何保证缓存与数据库的数据一致性？', '保证缓存一致性的策略：1）先更新数据库再删除缓存（延迟双删）；2）消息队列异步同步；3）缓存设置较短 TTL（最终一致）；4）使用 CDC（监听 binlog）同步。最常用模式：更新数据库后立即删除缓存，下次读取时重建，配合短 TTL 兜底。', '["缓存一致性", "延迟双删", "CDC", "最终一致性"]', '["提示1: 先更新数据库再删缓存", "提示2: 短 TTL 兜底保证一致性"]', '["缓存", "一致性", "数据"]', 'official'),
(156, 6, 2, 'ORM vs SQL', 'Go 中 ORM 和手写 SQL 各自的优缺点是什么？', 'ORM 优点：开发效率高、自动映射、迁移方便、减少样板代码。缺点：复杂查询性能差、N+1 问题、SQL 不可见难优化、学习成本。手写 SQL 优点：性能可控、优化灵活、完全掌握查询逻辑。缺点：开发效率低、需手动映射、易出错。建议：简单 CRUD 用 ORM，复杂查询用 SQL。', '["ORM", "手写 SQL", "sqlx", "GORM"]', '["提示1: ORM 适合简单 CRUD", "提示2: 复杂查询推荐手写 SQL"]', '["ORM", "SQL", "最佳实践"]', 'official'),

-- L3 中级 (ID 157-162)
(157, 6, 3, '分库分表', '数据库分库分表的策略和挑战是什么？Go 中如何实现？', '分库分表策略：水平分片（按 ID/时间范围或 Hash 取模）、垂直分片（按业务拆分字段）。挑战：跨分片查询、分布式事务、全局主键、分片扩容。Go 实现：使用 sharding 中间件（ShardingSphere、Vitess），或应用层实现分片路由规则。', '["分库分表", "水平分片", "一致性哈希", "Vitess"]', '["提示1: 范围分片和哈希分片是主流", "提示2: 跨分片查询是最大挑战"]', '["分片", "数据库", "扩展"]', 'official'),
(158, 6, 3, '主键生成', '分布式系统中全局唯一 ID 生成的方案有哪些？', '全局 ID 生成方案：1）UUID（唯一但无序，不适合做索引）；2）Snowflake（雪花算法，高性能趋势递增）；3）数据库自增 + 分步长；4）Redis INCR（简单但依赖 redis）；5）号段模式（Leaf 美团）。Snowflake 最常用，包含时间戳+机器ID+序列号。', '["Snowflake", "UUID", "全局 ID", "趋势递增"]', '["提示1: Snowflake 趋势递增有利索引", "提示2: UUID 无序不适合聚簇索引"]', '["分布式", "ID 生成", "算法"]', 'official'),
(159, 6, 3, 'Elasticsearch', 'Go 中如何与 Elasticsearch 集成？常用操作有哪些？', 'Go 集成 ES 使用 elastic/go-elasticsearch 官方客户端。基本操作：创建索引（CreateIndex）、索引文档（Index）、搜索（Search）支持 DSL 查询、聚合（Aggregation）。推荐使用 Bulk 批量操作提高写入性能。搜索用 term/match/bool 等查询 DSL。', '["Elasticsearch", "go-elasticsearch", "DSL", "索引"]', '["提示1: Bulk 批量写入提高性能", "提示2: bool 查询组合多个条件"]', '["Elasticsearch", "搜索引擎", "数据"]', 'official'),
(160, 6, 3, '消息队列', 'Go 中如何使用 Kafka？sarama 库的基本用法。', 'sarama 是 Go 的 Kafka 客户端。生产者：sync/async 两种，发送消息到 topic。消费者：ConsumerGroup 实现消费组，支持 rebalance。配置：acks、retries、batch size 影响性能。推荐使用 Sarama Cluster 保证消费偏移量正确管理。', '["Kafka", "sarama", "消息队列", "ConsumerGroup"]', '["提示1: ConsumerGroup 实现消费组", "提示2: acks 配置影响消息可靠性"]', '["Kafka", "消息队列", "流处理"]', 'official'),
(161, 6, 3, '数据备份', 'Go 中如何实现数据库定期备份和恢复？', 'Go 实现备份方式：1）使用 exec.Command 调用数据库原生备份命令（mysqldump/pg_dump）；2）使用第三方备份库；3）定时任务（cron 库 robfig/cron）。恢复时：先创建空数据库，再执行备份文件中的 SQL。建议备份文件压缩后上传到对象存储（S3/OSS）。', '["备份", "mysqldump", "cron", "对象存储"]', '["提示1: robfig/cron 实现定时任务", "提示2: 备份文件压缩后存储"]', '["备份", "运维", "数据安全"]', 'official'),
(162, 6, 3, '连接泄漏', 'Go 中如何排查数据库连接泄漏？有哪些预防措施？', '连接泄漏指连接未归还连接池。排查：1）监控 SetMaxOpenConns 是否达到上限；2）使用 db.Stats() 获取连接池统计（InUse/Idle）；3）pprof goroutine 查看阻塞的 goroutine。预防：确保每次 Query 后调用 rows.Close()，事务正确 Commit/Rollback，使用 defer 归还资源。', '["连接泄漏", "db.Stats", "InUse", "rows.Close"]', '["提示1: db.Stats 查看连接池状态", "提示2: defer rows.Close() 防泄漏"]', '["排查", "数据库", "连接池"]', 'official'),

-- L4 高级 (ID 163-168)
(163, 6, 4, '分布式存储', '分布式存储系统的 CAP 原理和一致性级别是什么？', 'CAP 原理：一致性（Consistency）、可用性（Availability）、分区容错（Partition Tolerance）三者最多满足两个。实际通常选择 AP 或 CP。一致性级别：强一致性（CP 系统）、最终一致性（AP 系统）、因果一致性、读己之写一致性。ETCD 选 CP，Cassandra 选 AP。', '["CAP", "一致性", "可用性", "分区容错"]', '["提示1: 分区容错是分布式系统的必须", "提示2: AP 和 CP 是实际选择"]', '["分布式", "CAP", "存储"]', 'official'),
(164, 6, 4, 'LSM-Tree', 'LSM-Tree 存储引擎的原理是什么？与 B+Tree 对比有何优劣？', 'LSM-Tree（Log-Structured Merge-Tree）将写入先记内存表（MemTable），达到阈值后冻结为不可变 SSTable 并落盘，后台合并（Compaction）整理层级。优势：写入吞吐高（顺序写）、压缩比好。劣势：读放大（需检查多层）、合并写放大。B+Tree 读性能好，写性能差。', '["LSM-Tree", "SSTable", "Compaction", "B+Tree"]', '["提示1: LSM-Tree 写入吞吐高", "提示2: B+Tree 读性能更优"]', '["存储引擎", "LSM-Tree", "B+Tree"]', 'official'),
(165, 6, 4, 'NewSQL', '什么是 NewSQL 数据库？TiDB 的架构原理是什么？', 'NewSQL 结合分布式存储和 SQL 能力，兼具 NoSQL 的扩展性和 SQL 的事务性。TiDB 是 Go 实现的 NewSQL：TiDB Server（SQL 层，无状态）、TiKV（分布式 KV 存储，基于 Raft）、PD（调度中心）。支持 MySQL 协议、水平扩展、分布式事务（ Percolator 模型）。', '["NewSQL", "TiDB", "TiKV", "Raft", "Percolator"]', '["提示1: TiDB 兼容 MySQL 协议", "提示2: TiKV 基于 Raft 保障一致性"]', '["NewSQL", "TiDB", "分布式数据库"]', 'official'),
(166, 6, 4, '缓存穿透', '什么是缓存穿透、缓存击穿、缓存雪崩？如何解决？', '缓存穿透：查询不存在的数据（数据库也无），大量请求穿透 DB。解决：布隆过滤器或缓存空值。缓存击穿：热点 key 失效，大量并发请求 DB。解决：互斥锁重建缓存。缓存雪崩：大量 key 同时过期，流量直冲 DB。解决：随机过期时间、二级缓存、限流降级。', '["缓存穿透", "缓存击穿", "缓存雪崩", "布隆过滤器"]', '["提示1: 布隆过滤器解决穿透", "提示2: 随机过期时间防雪崩"]', '["缓存", "高并发", "保护"]', 'official'),
(167, 6, 4, '数据复制', '数据库主从复制和数据同步的实现原理是什么？', '主从复制原理：主库记录 binlog（二进制日志），从库 IO 线程拉取并写入 relay log，SQL 线程重放 relay log 完成同步。Go 中可使用 go-mysql-elasticsearch 监听 binlog 同步到 ES，或用 Canal/Debezium 实现 CDC（Change Data Capture）。', '["主从复制", "binlog", "CDC", "Canal"]', '["提示1: binlog 记录数据库变更", "提示2: CDC 监听 binlog 同步数据"]', '["复制", "数据同步", "CDC"]', 'official'),
(168, 6, 4, '存储选型', 'Go 微服务中如何选择存储方案？不同场景的推荐？', '存储选型指南：1）关系型数据用 MySQL/PostgreSQL（ACID 事务）；2）缓存用 Redis（高性能读写）；3）搜索引擎用 Elasticsearch（全文搜索）；4）时序数据用 InfluxDB/Prometheus；5）对象存储用 S3/OSS（文件/图片）；6）图数据用 Neo4j；7）消息队列用 Kafka/RabbitMQ。根据访问模式、一致性、扩展性需求选择。', '["存储选型", "MySQL", "Redis", "ES"]', '["提示1: 关系型数据库保证事务", "提示2: 缓存和持久化分离"]', '["存储", "选型", "架构"]', 'official'),

-- ====================================================================
-- 领域 7: 云原生 (ID 169-188)
-- L1 入门 (ID 169-173)
-- ====================================================================
(169, 7, 1, 'Dockerfile', '如何编写高效的 Go Dockerfile？多阶段构建是什么？', '多阶段构建是 Go Dockerfile 的最佳实践：第一阶段用 golang:alpine 编译出静态二进制（CGO_ENABLED=0），第二阶段用 scratch/alpine 仅拷贝二进制运行。优点：镜像极小（<20MB）、减少攻击面、构建和运行环境分离。', '["Dockerfile", "多阶段构建", "scratch", "alpine"]', '["提示1: 多阶段构建减小镜像体积", "提示2: CGO_ENABLED=0 编译静态二进制"]', '["Docker", "容器化", "构建"]', 'official'),
(170, 7, 1, 'Docker 基础', 'Docker 的核心概念（镜像/容器/仓库）是什么？', 'Docker 核心概念：镜像（Image）- 只读模板，包含运行环境和应用；容器（Container）- 镜像的运行实例，可读写层；仓库（Registry）- 存储分发镜像的场所（Docker Hub/私有仓库）。Go 应用通过 Dockerfile 构建镜像，运行在容器中。', '["Docker", "镜像", "容器", "仓库"]', '["提示1: 镜像是只读模板", "提示2: 容器是镜像的运行实例"]', '["Docker", "容器", "基础"]', 'official'),
(171, 7, 1, 'K8s Pod', 'Kubernetes 中 Pod 的基本概念和作用是什么？', 'Pod 是 Kubernetes 的最小调度单元，包含一个或多个容器（共享网络和存储）。Pod 提供：1）共享 IP 和端口空间；2）共享存储卷；3）共享进程间通信。Pod 是短暂的，可被调度器杀死和迁移。通常一个 Pod 运行一个主容器（应用）加可选 Sidecar 容器。', '["Pod", "Kubernetes", "调度单元", "Sidecar"]', '["提示1: Pod 是 K8s 最小调度单元", "提示2: 同 Pod 容器共享网络和存储"]', '["Kubernetes", "Pod", "容器编排"]', 'official'),
(172, 7, 1, 'K8s Deployment', 'Kubernetes Deployment 的作用是什么？如何使用？', 'Deployment 管理 Pod 的声明式更新，支持：1）期望副本数（Replicas）；2）滚动更新策略（RollingUpdate）；3）回滚到历史版本；4）自动重启故障 Pod。通过 YAML 定义 Deployment，kubectl apply 部署。更新镜像版本时自动执行滚动更新。', '["Deployment", "滚动更新", "Replicas", "kubectl"]', '["提示1: Deployment 管理 Pod 生命周期", "提示2: 滚动更新不中断服务"]', '["Kubernetes", "Deployment", "调度"]', 'official'),
(173, 7, 1, 'K8s Service', 'Kubernetes Service 的类型和用途是什么？', 'Kubernetes Service 提供稳定的网络入口访问 Pod。类型：ClusterIP（集群内访问，默认）、NodePort（节点端口暴露）、LoadBalancer（云负载均衡器）、ExternalName（DNS 映射）。Service 通过 Label Selector 匹配后端的 Pod 实现流量分发。', '["Service", "ClusterIP", "NodePort", "LoadBalancer"]', '["提示1: Service 提供稳定访问入口", "提示2: Selector 通过标签匹配 Pod"]', '["Kubernetes", "Service", "网络"]', 'official'),

-- L2 初级 (ID 174-178)
(174, 7, 2, 'ConfigMap', 'Kubernetes ConfigMap 和 Secret 的区别及使用方法？', 'ConfigMap 存储非敏感配置（环境变量、配置文件），Secret 存储敏感信息（密码、证书）。两者均可通过环境变量注入或 Volume 挂载到 Pod。Secret 使用 Base64 编码（不是加密），建议结合 SealedSecret 或外部密钥管理。', '["ConfigMap", "Secret", "环境变量", "Volume 挂载"]', '["提示1: ConfigMap 用于非敏感数据", "提示2: Secret 不是加密而是编码"]', '["Kubernetes", "配置", "安全"]', 'official'),
(175, 7, 2, 'Helm', 'Helm chart 的结构和用途是什么？', 'Helm 是 Kubernetes 包管理器。Chart 结构：Chart.yaml（元数据）、values.yaml（默认配置）、templates/（Go template 模板 YAML）、_helpers.tpl（模板辅助函数）。通过 Helm template 渲染参数化 YAML，helm install/upgrade 部署。适合应用分发的标准方式。', '["Helm", "Chart", "values.yaml", "模板"]', '["提示1: Helm 是 K8s 包管理器", "提示2: values.yaml 定义可配置参数"]', '["Helm", "Kubernetes", "部署"]', 'official'),
(176, 7, 2, '水平扩缩', 'Kubernetes HPA（水平自动扩缩）的原理是什么？', 'HPA 根据 CPU/内存指标或自定义指标自动调整 Pod 副本数。原理：HPA 控制器定期查询 Metrics Server 获取 Pod 资源使用率，根据目标利用率计算期望副本数。支持行为配置（behavior）：稳定窗口、扩缩策略、速率限制。Go 应用需正确设置 resource requests/limits。', '["HPA", "自动扩缩", "Metrics Server", "resource"]', '["提示1: resource requests 是调度依据", "提示2: HPA 支持自定义指标"]', '["Kubernetes", "自动扩缩", "弹性"]', 'official'),
(177, 7, 2, 'Ingress', 'Kubernetes Ingress 的作用是什么？如何配置？', 'Ingress 提供 HTTP/HTTPS 路由到 Service 的规则，是集群入口流量管理。通过 Ingress Controller（如 Nginx Ingress、Traefik）实现。支持：基于域名和路径路由、TLS 终止、限流、重定向。配置示例：host 匹配域名，path 匹配路径，backend 指向 Service。', '["Ingress", "路由", "TLS", "Ingress Controller"]', '["提示1: Ingress 管理入口流量", "提示2: Ingress Controller 是实现组件"]', '["Kubernetes", "Ingress", "网络"]', 'official'),
(178, 7, 2, '健康探针', 'Kubernetes 中 liveness、readiness、startup 探针的区别是什么？', '三种探针：livenessProbe（存活探针，检测是否运行，失败重启容器）、readinessProbe（就绪探针，检测是否可服务，失败移除 Service 端点）、startupProbe（启动探针，防止慢启动容器被 liveness 误杀）。Go HTTP 服务应分别提供 /healthz 和 /readyz 端点。', '["livenessProbe", "readinessProbe", "startupProbe", "探针"]', '["提示1: liveness 失败重启容器", "提示2: readiness 失败摘除流量"]', '["Kubernetes", "健康检查", "探针"]', 'official'),

-- L3 中级 (ID 179-183)
(179, 7, 3, '容器调度', 'Kubernetes 调度器的工作原理和调度策略是什么？', 'K8s 调度器通过两阶段选择 Pod 运行的 Node：1）过滤（Predicates）：检查节点资源、端口冲突、污点容忍等；2）评分（Priorities）：按资源利用率、亲和性等打分。支持自定义调度器、节点亲和性（nodeAffinity）、Pod 亲和性/反亲和性（podAffinity/podAntiAffinity）。', '["调度器", "过滤", "评分", "亲和性"]', '["提示1: 过滤阶段排除不满足的节点", "提示2: 评分阶段选择最优节点"]', '["调度", "Kubernetes", "调度策略"]', 'official'),
(180, 7, 3, 'Operator', '什么是 Kubernetes Operator？Go 中如何使用 operator-sdk 开发 Operator？', 'Operator 是用自定义控制器管理有状态应用（如 etcd、Prometheus）的模式，扩展 K8s API。使用 operator-sdk + controller-runtime 开发：定义 CRD（Custom Resource Definition）、实现 Reconciler（调谐逻辑，确保实际状态符合期望状态）。应用将 Kubernetes 视为控制平面。', '["Operator", "CRD", "operator-sdk", "Reconciler"]', '["提示1: Operator 管理有状态应用", "提示2: Reconciler 实现调谐循环"]', '["Operator", "Kubernetes", "自动化"]', 'official'),
(181, 7, 3, '服务网格集成', '在 Kubernetes 中集成 Istio 服务网格的步骤和好处是什么？', '集成 Istio：1）安装 Istio 控制面（istiod）；2）给命名空间注入 Sidecar（istio-injection=enabled）；3）部署应用，Envoy 代理自动注入。好处：mTLS 加密、流量管理（灰度/蓝绿）、可观测性（Kiali/Jaeger/Grafana）、访问控制（AuthorizationPolicy）。', '["Istio", "Envoy", "Sidecar 注入", "mTLS"]', '["提示1: istio-injection 标签启用注入", "提示2: Kiali 可视化服务网格拓扑"]', '["Istio", "服务网格", "Kubernetes"]', 'official'),
(182, 7, 3, '资源限制', 'Kubernetes 中如何为 Go 服务配置资源请求和限制？', 'resources.requests（请求量，调度保证）和 resources.limits（上限，超限被 OOMKill）。Go 服务建议：设置 requests = limits 保证 QoS Guaranteed 类。注意 Go 运行时不会主动归还内存给 OS，需设置 GOMEMLIMIT（Go 1.19+）控制内存使用上限，避免 OOM。', '["resource requests/limits", "Guaranteed QoS", "GOMEMLIMIT", "OOM"]', '["提示1: requests=limits 保 QoS", "提示2: GOMEMLIMIT 控制 Go 内存上限"]', '["Kubernetes", "资源管理", "Go 内存"]', 'official'),
(183, 7, 3, '声明式 API', 'Kubernetes 声明式 API 的设计哲学是什么？与命令式 API 对比？', '声明式 API 描述期望状态（Spec），控制器持续调谐使实际状态（Status）匹配期望状态。对比命令式：声明式聚焦"What"（要什么），命令式聚焦"How"（怎么做）。优势：自修复（故障自动恢复）、版本化（etcd 存储）、一致性、自文档（YAML 即文档）。', '["声明式 API", "期望状态", "调谐循环", "自修复"]', '["提示1: 声明期望状态而非指令", "提示2: 控制器持续调谐实际状态"]', '["Kubernetes", "API", "设计哲学"]', 'official'),

-- L4 高级 (ID 184-188)
(184, 7, 4, '容器安全', 'Go 容器化应用的安全最佳实践有哪些？', '安全实践：1）使用 scratch/distroless 基础镜像减少攻击面；2）以非 root 用户运行（USER 指令）；3）只读根文件系统（readOnlyRootFilesystem）；4）限制系统调用（seccomp）；5）最小权限（SecurityContext）；6）镜像签名验证；7）定期扫描 CVE 漏洞（Trivy）。', '["容器安全", "scratch", "非 root", "seccomp"]', '["提示1: 非 root 用户降低风险", "提示2: Trivy 扫描镜像漏洞"]', '["安全", "容器", "最佳实践"]', 'official'),
(185, 7, 4, 'CNI 网络', 'Kubernetes CNI 网络模型的原理和常见插件有哪些？', 'CNI（Container Network Interface）定义容器网络标准：每个 Pod 有独立 IP，Pod 间无需 NAT 直接通信。常见插件：Calico（网络策略+BGP）、Flannel（overlay 网络）、Cilium（eBPF 驱动高性能）。CNI 负责分配 IP、配置网络接口和路由规则。', '["CNI", "Calico", "Cilium", "eBPF"]', '["提示1: 每个 Pod 有独立 IP", "提示2: Cilium 基于 eBPF 高性能"]', '["网络", "CNI", "Kubernetes"]', 'official'),
(186, 7, 4, 'K8s 扩展', 'Kubernetes API 扩展的方式有哪些？CRD vs API Aggregation 的区别？', 'K8s API 扩展方式：1）CRD（Custom Resource Definition）- 声明式定义新资源类型，控制器通过 controller-runtime 实现；2）API Aggregation - 在 API Server 后挂载自定义 API 服务，支持任意协议。CRD 简单通用，推荐大多数场景。API Aggregation 更灵活但实现更复杂。', '["CRD", "API Aggregation", "API 扩展", "controller-runtime"]', '["提示1: CRD 适合大多数场景", "提示2: API Aggregation 更灵活"]', '["Kubernetes", "API 扩展", "高级"]', 'official'),
(187, 7, 4, 'eBPF', 'eBPF 技术是什么？在云原生领域有哪些应用？', 'eBPF 是 Linux 内核的安全可编程扩展技术，允许在不修改内核代码或加载内核模块的情况下运行沙箱程序。云原生应用：Cilium（网络和安全策略）、Falco（安全监控）、Pixie（可观测性）、Hubble（网络可观测性）。eBPF 提供高性能的内核级观测和控制能力。', '["eBPF", "Cilium", "Falco", "内核编程"]', '["提示1: Cilium 基于 eBPF 实现网络", "提示2: eBPF 无需加载内核模块"]', '["eBPF", "云原生", "内核"]', 'official'),
(188, 7, 4, '云原生设计', '云原生应用的 12-Factor App 原则是什么？Go 应用如何实践？', '12-Factor 原则：1）基准代码（单代码库多部署）；2）依赖显式声明（go.mod）；3）配置环境变量；4）后端服务（视为附加资源）；5）构建/发布/运行分离；6）无状态进程；7）端口绑定（HTTP 服务）；8）并发（进程模型）；9）易处置（快速启动优雅关闭）；10）开发/生产一致；11）日志（事件流）；12）管理进程（一次性任务）。', '["12-Factor", "云原生原则", "无状态", "环境变量"]', '["提示1: 12-Factor 是云原生标准", "提示2: Go 天然适合 12-Factor"]', '["云原生", "12-Factor", "设计原则"]', 'official'),

-- ====================================================================
-- 领域 8: 系统设计 (ID 189-208)
-- L1 入门 (ID 189-193)
-- ====================================================================
(189, 8, 1, '设计原则', 'SOLID 原则中的单一职责原则（SRP）是什么？在 Go 中如何体现？', 'SRP 指一个类/模块应该只有一个引起它变化的原因。Go 中通过小而专注的接口（如 io.Reader）和职责清晰的包结构体现。避免在一个结构体或接口中混合不相关的职责。接口建议 1-3 个方法，超过则考虑拆分。', '["SRP", "单一职责", "接口设计", "内聚"]', '["提示1: 一个接口只做一件事", "提示2: io.Reader 是 SRP 典范"]', '["设计原则", "SOLID"]', 'official'),
(190, 8, 1, '分层架构', '经典三层架构（表现层/业务层/数据层）在 Go 中如何实现？', '三层架构：handler（HTTP 处理，接收请求和返回响应）-> service（业务逻辑）-> repository（数据访问）。Go 中通过接口解耦层间依赖，handler 依赖 service 接口，service 依赖 repository 接口。分层使代码关注点分离，易于测试和维护。', '["三层架构", "分层", "handler/service/repository", "关注点分离"]', '["提示1: handler 处理 HTTP 请求", "提示2: 接口解耦层间依赖"]', '["架构", "分层", "Go"]', 'official'),
(191, 8, 1, '模块化', 'Go 中如何实现模块化设计？包的组织原则是什么？', 'Go 模块化通过 package 实现：1）按业务领域组织包（按功能而非层级）；2）避免循环依赖；3）合理使用 internal 包隐藏内部实现；4）包名简洁有意义；5）避免过大的包（一个包超过 3000 行考虑拆分）。好的模块化提高可维护性和复用性。', '["模块化", "包设计", "internal", "循环依赖"]', '["提示1: 按领域而非层级组织", "提示2: internal 包限制外部访问"]', '["模块化", "包设计", "架构"]', 'official'),
(192, 8, 1, '耦合与内聚', '高内聚低耦合的设计原则是什么？在 Go 中如何实践？', '高内聚指相关功能放在同一模块，低耦合指模块间依赖最小化。Go 实践：1）通过接口定义模块间契约；2）依赖注入而非直接创建依赖；3）事件驱动解耦；4）包级别的责任明确，避免"工具类"大包。接口定义在消费者包中（而非实现者包）进一步降低耦合。', '["内聚", "耦合", "接口契约", "依赖注入"]', '["提示1: 接口在消费者包定义", "提示2: 依赖注入降低耦合"]', '["设计原则", "耦合内聚"]', 'official'),
(193, 8, 1, '设计模式', 'Go 中常用的设计模式有哪些？与 OOP 语言的实现有何不同？', 'Go 常用设计模式：1）单例（sync.Once）；2）工厂（函数返回接口）；3）策略（接口多态）；4）装饰器（中间件模式）；5）观察者（channel + goroutine）；6）选项模式（Functional Options）。Go 没有继承，使用组合 + 接口实现模式，更简洁灵活。', '["设计模式", "单例", "选项模式", "策略模式"]', '["提示1: sync.Once 实现单例", "提示2: 选项模式优雅处理可选参数"]', '["设计模式", "Go", "OOP"]', 'official'),

-- L2 初级 (ID 194-198)
(194, 8, 2, 'CQRS', '什么是 CQRS 模式？Go 中如何实现？', 'CQRS（命令查询职责分离）将读操作（Query）和写操作（Command）分离为不同的模型。Go 实现：命令通过 Command Handler 处理（写入数据库/事件），查询通过 Query Handler 处理（从读取模型/缓存查询）。优势：读写优化独立、扩展性更好。可能与事件溯源结合使用。', '["CQRS", "命令查询分离", "Query Handler", "Command Handler"]', '["提示1: 读模型和写模型分离", "提示2: CQRS 提升扩展性"]', '["CQRS", "架构模式", "设计"]', 'official'),
(195, 8, 2, '事件溯源', '什么是事件溯源（Event Sourcing）？与 CQRS 的关系是什么？', '事件溯源将状态变更存储为事件序列，而非当前状态。重建状态时重放所有事件。与 CQRS 常结合使用：Command 端产生事件存储到事件存储，Query 端消费事件构建读模型。优势：完整审计日志、时间旅行调试、可追溯。挑战：事件版本管理、快照优化。', '["事件溯源", "事件存储", "重放", "时间旅行"]', '["提示1: 事件是不可变的", "提示2: 快照优化重放性能"]', '["事件溯源", "架构模式"]', 'official'),
(196, 8, 2, '六边形架构', '六边形架构（Ports & Adapters）的原理是什么？在 Go 中如何实现？', '六边形架构核心是业务逻辑在中心（Domain），通过 Port（接口）与外部交互，Adapter（实现）适配具体技术（HTTP/gRPC/数据库）。Go 实现：domain 包定义核心业务逻辑和 Port 接口；adapter 包实现适配器（MySQL/GORM/Redis）。测试时可用 mock adapter 替换。', '["六边形架构", "Ports & Adapters", "domain", "adapter"]', '["提示1: 业务逻辑在中心不受外部影响", "提示2: adapter 可替换便于测试"]', '["架构", "六边形", "DDD"]', 'official'),
(197, 8, 2, '限流设计', '高并发系统限流的设计方案有哪些？', '限流方案：1）单机限流（令牌桶/漏桶）；2）分布式限流（Redis + Lua 脚本实现计数器）；3）接入层限流（Nginx/BIG-IP）；4）熔断（Hystrix 模式）；5）队列削峰（消息队列缓冲）。Go 中 x/time/rate 做单机限流，Redis 集群做分布式限流。', '["限流方案", "分布式限流", "Redis Lua", "队列削峰"]', '["提示1: 分布式限流用 Redis 脚本", "提示2: 队列削峰保护下游"]', '["限流", "高并发", "设计"]', 'official'),
(198, 8, 2, '幂等性', '分布式系统中幂等性设计的常见方案有哪些？', '幂等性方案：1）唯一请求号（客户端生成 UUID，服务端去重表）；2）数据库唯一索引（防重复插入）；3）状态机（检测状态变化防重复处理）；4）Token 机制（预生成 token，处理时校验并删除）；5）利用业务属性（如订单号天然幂等）。Go 实现可用 Redis SETNX 做去重。', '["幂等性", "去重表", "Token", "SETNX"]', '["提示1: 唯一请求号是最常用方案", "提示2: Redis SETNX 实现分布式锁"]', '["幂等", "分布式", "设计"]', 'official'),

-- L3 中级 (ID 199-203)
(199, 8, 3, '高并发设计', '高并发系统的设计要素和应对策略是什么？', '高并发设计要素：1）无状态（水平扩展的基石）；2）缓存（多层缓存减少 DB 压力）；3）异步（削峰填谷）；4）分片（水平拆分数据）；5）读写分离（主从复制）；6）连接池（复用连接资源）；7）限流熔断（自我保护）；8）CDN（静态资源加速）。Go 的 goroutine 天然适合高并发。', '["高并发", "水平扩展", "缓存", "异步"]', '["提示1: 无状态是实现水平扩展的前提", "提示2: 多层缓存减少数据库压力"]', '["高并发", "设计", "扩展"]', 'official'),
(200, 8, 3, '秒杀设计', '如何设计一个秒杀系统？关键技术点是什么？', '秒杀系统设计要点：1）前端限流（按钮灰化、验证码）；2）Nginx 层限流（limit_req）；3）Redis 预减库存（原子操作）；4）消息队列异步下单（削峰）；5）数据库乐观锁（版本号防超卖）；6）静态资源 CDN；7）独立部署秒杀服务隔离影响。核心思想：层层过滤，最终到达 DB 的请求极少。', '["秒杀", "预减库存", "削峰", "乐观锁"]', '["提示1: 层层过滤减少下游压力", "提示2: Redis 原子操作防超卖"]', '["秒杀", "高并发", "系统设计"]', 'official'),
(201, 8, 3, '分布式锁', '分布式锁的实现方案和注意事项是什么？', '分布式锁方案：1）Redis SETNX + Lua（推荐 Redlock 算法）；2）etcd 租赁（lease + 续约）；3）ZooKeeper 临时顺序节点。注意事项：1）锁必须设置超时避免死锁；2）确保释放自己的锁（value 对比）；3）考虑锁重入；4）考虑时钟偏移问题。Go 中可用 Redis 的 SET EX NX 或 etcd 的 concurrency/stm 包。', '["分布式锁", "Redlock", "SETNX", "etcd"]', '["提示1: 锁超时避免死锁", "提示2: Redlock 是 Redis 官方推荐"]', '["分布式锁", "分布式", "设计"]', 'official'),
(202, 8, 3, '一致性哈希', '一致性哈希算法的原理和应用场景是什么？', '一致性哈希将哈希值空间组织成环，节点和数据都映射到环上，数据沿环顺时针找到第一个节点。优点：增减节点只影响相邻小部分数据，而非全部重新哈希。应用：分布式缓存（Redis Cluster）、负载均衡。引入虚拟节点解决数据倾斜问题。', '["一致性哈希", "哈希环", "虚拟节点", "数据倾斜"]', '["提示1: 增减节点只影响相邻数据", "提示2: 虚拟节点解决数据倾斜"]', '["一致性哈希", "分布式", "算法"]', 'official'),
(203, 8, 3, '流量治理', '微服务流量治理的策略和工具是什么？', '流量治理策略：1）超时控制（context.WithTimeout）；2）重试（指数退避+抖动）；3）限流（令牌桶/漏桶）；4）熔断（熔断器模式）；5）降级（返回降级结果）；6）灰度（权重路由）。工具：Envoy/Istio（代理层）、hystrix-go/gobreaker（应用层）。', '["流量治理", "超时", "熔断", "降级"]', '["提示1: 超时防止资源长期占用", "提示2: 降级提供有损服务"]', '["流量治理", "服务治理", "微服务"]', 'official'),

-- L4 高级 (ID 204-208)
(204, 8, 4, '分布式共识', '分布式共识算法 Raft 的核心机制是什么？', 'Raft 通过选举领导者（Leader Election）和日志复制（Log Replication）实现共识。关键机制：1）Term 任期和随机超时选举；2）日志条目由 Leader 推送到 Follower（多数派写入即提交）；3）安全性保证（只有最新日志的节点才能当选 Leader）。Go 实现：etcd/raft、hashicorp/raft。', '["Raft", "领导者选举", "日志复制", "共识算法"]', '["提示1: Raft 通过多数派达成共识", "提示2: etcd/raft 是 Go 实现"]', '["Raft", "分布式共识", "算法"]', 'official'),
(205, 8, 4, 'Gossip 协议', 'Gossip 协议的原理和应用场景是什么？', 'Gossip 协议通过节点间周期性的随机信息交换实现信息最终一致。每个周期每个节点随机选择几个节点同步信息。特点：去中心化、容错性好、最终一致。应用：Cassandra/Redis Cluster 的节点发现、Consul 的成员管理。Go 实现：hashicorp/memberlist。', '["Gossip", "最终一致", "去中心化", "memberlist"]', '["提示1: 随机传播最终全部知晓", "提示2: memberlist 是 Go 实现"]', '["Gossip", "分布式协议", "一致性"]', 'official'),
(206, 8, 4, '分布式 ID', '分布式 ID 生成服务如何设计？Snowflake 算法的 Go 实现要点？', '分布式 ID 生成要求：全局唯一、趋势递增、高可用、高性能。Snowflake 算法：1 bit 符号位 + 41 bit 毫秒时间戳 + 10 bit 机器 ID + 12 bit 序列号。Go 实现要点：1）时间戳回拨处理（等待或错误回退）；2）机器 ID 配置和管理；3）序列号溢出处理；4）性能优化（预生成批量 ID）。', '["Snowflake 实现", "时间回拨", "机器 ID", "趋势递增"]', '["提示1: 处理时钟回拨是难点", "提示2: 批量预生成提高性能"]', '["ID 生成", "Snowflake", "分布式"]', 'official'),
(207, 8, 4, '混沌工程', '什么是混沌工程？Go 服务中如何实施？', '混沌工程通过主动注入故障（网络延迟、节点宕机、CPU 飙高等）验证系统韧性。原则：1）定义稳态；2）提出假设；3）注入故障；4）观察并改进。Go 中工具：Chaos Mesh（K8s 平台）、litmus（云原生混沌工程）、gremlin-go（故障注入库）。对分布式系统尤为重要。', '["混沌工程", "故障注入", "Chaos Mesh", "韧性"]', '["提示1: 主动注入故障验证韧性", "提示2: Chaos Mesh 是 K8s 混沌平台"]', '["混沌工程", "可靠性", "测试"]', 'official'),
(208, 8, 4, '架构演进', '从单体到微服务的架构演进策略和注意事项是什么？', '演进策略：1）绞杀者模式（Strangler Fig）- 逐步将功能从单体剥离为新服务；2）按业务域拆分（DDD 限界上下文）；3）先拆分非核心功能（用户认证、通知）；4）数据库解耦最晚拆分。注意事项：避免过度拆分（过微服务）、服务间通信复杂度、分布式事务、运维成本。多数情况下从单体开始演进，不要一开始就上微服务。', '["架构演进", "绞杀者模式", "DDD", "微服务拆分"]', '["提示1: 绞杀者模式逐步迁移", "提示2: 不要一开始就用微服务"]', '["架构演进", "微服务", "DDD"]', 'official');